// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockterminalcontroller

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/terminal/adapter"
	"github.com/alexandremahdhaoui/forge-ui/internal/terminal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionController creates a new instance of MockSessionController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionController {
	mock := &MockSessionController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionController is an autogenerated mock type for the SessionController type
type MockSessionController struct {
	mock.Mock
}

type MockSessionController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionController) EXPECT() *MockSessionController_Expecter {
	return &MockSessionController_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockSessionController
func (_mock *MockSessionController) Start(cfg types.TerminalConfig, termIO adapter.TerminalIO) error {
	ret := _mock.Called(cfg, termIO)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.TerminalConfig, adapter.TerminalIO) error); ok {
		r0 = returnFunc(cfg, termIO)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionController_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockSessionController_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - cfg types.TerminalConfig
//   - termIO adapter.TerminalIO
func (_e *MockSessionController_Expecter) Start(cfg interface{}, termIO interface{}) *MockSessionController_Start_Call {
	return &MockSessionController_Start_Call{Call: _e.mock.On("Start", cfg, termIO)}
}

func (_c *MockSessionController_Start_Call) Run(run func(cfg types.TerminalConfig, termIO adapter.TerminalIO)) *MockSessionController_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.TerminalConfig
		if args[0] != nil {
			arg0 = args[0].(types.TerminalConfig)
		}
		var arg1 adapter.TerminalIO
		if args[1] != nil {
			arg1 = args[1].(adapter.TerminalIO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionController_Start_Call) Return(err error) *MockSessionController_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionController_Start_Call) RunAndReturn(run func(cfg types.TerminalConfig, termIO adapter.TerminalIO) error) *MockSessionController_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockSessionController
func (_mock *MockSessionController) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionController_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockSessionController_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockSessionController_Expecter) Stop() *MockSessionController_Stop_Call {
	return &MockSessionController_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockSessionController_Stop_Call) Run(run func()) *MockSessionController_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionController_Stop_Call) Return(err error) *MockSessionController_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionController_Stop_Call) RunAndReturn(run func() error) *MockSessionController_Stop_Call {
	_c.Call.Return(run)
	return _c
}
