// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewPortfolioService creates a new instance of PortfolioService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortfolioService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortfolioService {
	mock := &PortfolioService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PortfolioService is an autogenerated mock type for the PortfolioService type
type PortfolioService struct {
	mock.Mock
}

type PortfolioService_Expecter struct {
	mock *mock.Mock
}

func (_m *PortfolioService) EXPECT() *PortfolioService_Expecter {
	return &PortfolioService_Expecter{mock: &_m.Mock}
}

// GetPortfolio provides a mock function for the type PortfolioService
func (_mock *PortfolioService) GetPortfolio(baseDir string, name string, sortMode string) (types.PortfolioPageData, error) {
	ret := _mock.Called(baseDir, name, sortMode)

	if len(ret) == 0 {
		panic("no return value specified for GetPortfolio")
	}

	var r0 types.PortfolioPageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (types.PortfolioPageData, error)); ok {
		return returnFunc(baseDir, name, sortMode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) types.PortfolioPageData); ok {
		r0 = returnFunc(baseDir, name, sortMode)
	} else {
		r0 = ret.Get(0).(types.PortfolioPageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(baseDir, name, sortMode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PortfolioService_GetPortfolio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPortfolio'
type PortfolioService_GetPortfolio_Call struct {
	*mock.Call
}

// GetPortfolio is a helper method to define mock.On call
//   - baseDir string
//   - name string
//   - sortMode string
func (_e *PortfolioService_Expecter) GetPortfolio(baseDir interface{}, name interface{}, sortMode interface{}) *PortfolioService_GetPortfolio_Call {
	return &PortfolioService_GetPortfolio_Call{Call: _e.mock.On("GetPortfolio", baseDir, name, sortMode)}
}

func (_c *PortfolioService_GetPortfolio_Call) Run(run func(baseDir string, name string, sortMode string)) *PortfolioService_GetPortfolio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PortfolioService_GetPortfolio_Call) Return(portfolioPageData types.PortfolioPageData, err error) *PortfolioService_GetPortfolio_Call {
	_c.Call.Return(portfolioPageData, err)
	return _c
}

func (_c *PortfolioService_GetPortfolio_Call) RunAndReturn(run func(baseDir string, name string, sortMode string) (types.PortfolioPageData, error)) *PortfolioService_GetPortfolio_Call {
	_c.Call.Return(run)
	return _c
}

// ListPortfolios provides a mock function for the type PortfolioService
func (_mock *PortfolioService) ListPortfolios(baseDir string, sortMode string) (types.PortfoliosPageData, error) {
	ret := _mock.Called(baseDir, sortMode)

	if len(ret) == 0 {
		panic("no return value specified for ListPortfolios")
	}

	var r0 types.PortfoliosPageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (types.PortfoliosPageData, error)); ok {
		return returnFunc(baseDir, sortMode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) types.PortfoliosPageData); ok {
		r0 = returnFunc(baseDir, sortMode)
	} else {
		r0 = ret.Get(0).(types.PortfoliosPageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(baseDir, sortMode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PortfolioService_ListPortfolios_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPortfolios'
type PortfolioService_ListPortfolios_Call struct {
	*mock.Call
}

// ListPortfolios is a helper method to define mock.On call
//   - baseDir string
//   - sortMode string
func (_e *PortfolioService_Expecter) ListPortfolios(baseDir interface{}, sortMode interface{}) *PortfolioService_ListPortfolios_Call {
	return &PortfolioService_ListPortfolios_Call{Call: _e.mock.On("ListPortfolios", baseDir, sortMode)}
}

func (_c *PortfolioService_ListPortfolios_Call) Run(run func(baseDir string, sortMode string)) *PortfolioService_ListPortfolios_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PortfolioService_ListPortfolios_Call) Return(portfoliosPageData types.PortfoliosPageData, err error) *PortfolioService_ListPortfolios_Call {
	_c.Call.Return(portfoliosPageData, err)
	return _c
}

func (_c *PortfolioService_ListPortfolios_Call) RunAndReturn(run func(baseDir string, sortMode string) (types.PortfoliosPageData, error)) *PortfolioService_ListPortfolios_Call {
	_c.Call.Return(run)
	return _c
}
