// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewWorkspaceService creates a new instance of WorkspaceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkspaceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkspaceService {
	mock := &WorkspaceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkspaceService is an autogenerated mock type for the WorkspaceService type
type WorkspaceService struct {
	mock.Mock
}

type WorkspaceService_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkspaceService) EXPECT() *WorkspaceService_Expecter {
	return &WorkspaceService_Expecter{mock: &_m.Mock}
}

// GetWorkspace provides a mock function for the type WorkspaceService
func (_mock *WorkspaceService) GetWorkspace(baseDir string, portfolio string, workspace string, sortMode string) (types.WorkspacePageData, error) {
	ret := _mock.Called(baseDir, portfolio, workspace, sortMode)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 types.WorkspacePageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) (types.WorkspacePageData, error)); ok {
		return returnFunc(baseDir, portfolio, workspace, sortMode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) types.WorkspacePageData); ok {
		r0 = returnFunc(baseDir, portfolio, workspace, sortMode)
	} else {
		r0 = ret.Get(0).(types.WorkspacePageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = returnFunc(baseDir, portfolio, workspace, sortMode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceService_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type WorkspaceService_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - baseDir string
//   - portfolio string
//   - workspace string
//   - sortMode string
func (_e *WorkspaceService_Expecter) GetWorkspace(baseDir interface{}, portfolio interface{}, workspace interface{}, sortMode interface{}) *WorkspaceService_GetWorkspace_Call {
	return &WorkspaceService_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", baseDir, portfolio, workspace, sortMode)}
}

func (_c *WorkspaceService_GetWorkspace_Call) Run(run func(baseDir string, portfolio string, workspace string, sortMode string)) *WorkspaceService_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *WorkspaceService_GetWorkspace_Call) Return(workspacePageData types.WorkspacePageData, err error) *WorkspaceService_GetWorkspace_Call {
	_c.Call.Return(workspacePageData, err)
	return _c
}

func (_c *WorkspaceService_GetWorkspace_Call) RunAndReturn(run func(baseDir string, portfolio string, workspace string, sortMode string) (types.WorkspacePageData, error)) *WorkspaceService_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}
