// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPageRenderer creates a new instance of PageRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPageRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PageRenderer {
	mock := &PageRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PageRenderer is an autogenerated mock type for the PageRenderer type
type PageRenderer struct {
	mock.Mock
}

type PageRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *PageRenderer) EXPECT() *PageRenderer_Expecter {
	return &PageRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type PageRenderer
func (_mock *PageRenderer) Render(route string) (string, error) {
	ret := _mock.Called(route)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(route)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(route)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(route)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PageRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type PageRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - route string
func (_e *PageRenderer_Expecter) Render(route interface{}) *PageRenderer_Render_Call {
	return &PageRenderer_Render_Call{Call: _e.mock.On("Render", route)}
}

func (_c *PageRenderer_Render_Call) Run(run func(route string)) *PageRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PageRenderer_Render_Call) Return(s string, err error) *PageRenderer_Render_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *PageRenderer_Render_Call) RunAndReturn(run func(route string) (string, error)) *PageRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}
