// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/controller"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPageRenderer creates a new instance of MockPageRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPageRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPageRenderer {
	mock := &MockPageRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPageRenderer is an autogenerated mock type for the PageRenderer type
type MockPageRenderer struct {
	mock.Mock
}

type MockPageRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPageRenderer) EXPECT() *MockPageRenderer_Expecter {
	return &MockPageRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type MockPageRenderer
func (_mock *MockPageRenderer) Render(route string) (controller.RenderResult, error) {
	ret := _mock.Called(route)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 controller.RenderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (controller.RenderResult, error)); ok {
		return returnFunc(route)
	}
	if returnFunc, ok := ret.Get(0).(func(string) controller.RenderResult); ok {
		r0 = returnFunc(route)
	} else {
		r0 = ret.Get(0).(controller.RenderResult)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(route)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPageRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockPageRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - route string
func (_e *MockPageRenderer_Expecter) Render(route interface{}) *MockPageRenderer_Render_Call {
	return &MockPageRenderer_Render_Call{Call: _e.mock.On("Render", route)}
}

func (_c *MockPageRenderer_Render_Call) Run(run func(route string)) *MockPageRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPageRenderer_Render_Call) Return(renderResult controller.RenderResult, err error) *MockPageRenderer_Render_Call {
	_c.Call.Return(renderResult, err)
	return _c
}

func (_c *MockPageRenderer_Render_Call) RunAndReturn(run func(route string) (controller.RenderResult, error)) *MockPageRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}
