// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockForgeService creates a new instance of MockForgeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForgeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForgeService {
	mock := &MockForgeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockForgeService is an autogenerated mock type for the ForgeService type
type MockForgeService struct {
	mock.Mock
}

type MockForgeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForgeService) EXPECT() *MockForgeService_Expecter {
	return &MockForgeService_Expecter{mock: &_m.Mock}
}

// GetForge provides a mock function for the type MockForgeService
func (_mock *MockForgeService) GetForge(baseDir string, portfolio string, workspace string, repo string) (types.ForgePageData, error) {
	ret := _mock.Called(baseDir, portfolio, workspace, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetForge")
	}

	var r0 types.ForgePageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) (types.ForgePageData, error)); ok {
		return returnFunc(baseDir, portfolio, workspace, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) types.ForgePageData); ok {
		r0 = returnFunc(baseDir, portfolio, workspace, repo)
	} else {
		r0 = ret.Get(0).(types.ForgePageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = returnFunc(baseDir, portfolio, workspace, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockForgeService_GetForge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForge'
type MockForgeService_GetForge_Call struct {
	*mock.Call
}

// GetForge is a helper method to define mock.On call
//   - baseDir string
//   - portfolio string
//   - workspace string
//   - repo string
func (_e *MockForgeService_Expecter) GetForge(baseDir interface{}, portfolio interface{}, workspace interface{}, repo interface{}) *MockForgeService_GetForge_Call {
	return &MockForgeService_GetForge_Call{Call: _e.mock.On("GetForge", baseDir, portfolio, workspace, repo)}
}

func (_c *MockForgeService_GetForge_Call) Run(run func(baseDir string, portfolio string, workspace string, repo string)) *MockForgeService_GetForge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockForgeService_GetForge_Call) Return(forgePageData types.ForgePageData, err error) *MockForgeService_GetForge_Call {
	_c.Call.Return(forgePageData, err)
	return _c
}

func (_c *MockForgeService_GetForge_Call) RunAndReturn(run func(baseDir string, portfolio string, workspace string, repo string) (types.ForgePageData, error)) *MockForgeService_GetForge_Call {
	_c.Call.Return(run)
	return _c
}
