// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkspaceMgmtService creates a new instance of MockWorkspaceMgmtService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceMgmtService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceMgmtService {
	mock := &MockWorkspaceMgmtService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkspaceMgmtService is an autogenerated mock type for the WorkspaceMgmtService type
type MockWorkspaceMgmtService struct {
	mock.Mock
}

type MockWorkspaceMgmtService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceMgmtService) EXPECT() *MockWorkspaceMgmtService_Expecter {
	return &MockWorkspaceMgmtService_Expecter{mock: &_m.Mock}
}

// CreateManagedWorkspace provides a mock function for the type MockWorkspaceMgmtService
func (_mock *MockWorkspaceMgmtService) CreateManagedWorkspace(namespace string, req types.CreateManagedWorkspaceRequest) (*types.ManagedWorkspaceDetail, error) {
	ret := _mock.Called(namespace, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateManagedWorkspace")
	}

	var r0 *types.ManagedWorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, types.CreateManagedWorkspaceRequest) (*types.ManagedWorkspaceDetail, error)); ok {
		return returnFunc(namespace, req)
	}
	if returnFunc, ok := ret.Get(0).(func(string, types.CreateManagedWorkspaceRequest) *types.ManagedWorkspaceDetail); ok {
		r0 = returnFunc(namespace, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ManagedWorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, types.CreateManagedWorkspaceRequest) error); ok {
		r1 = returnFunc(namespace, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceMgmtService_CreateManagedWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateManagedWorkspace'
type MockWorkspaceMgmtService_CreateManagedWorkspace_Call struct {
	*mock.Call
}

// CreateManagedWorkspace is a helper method to define mock.On call
//   - namespace string
//   - req types.CreateManagedWorkspaceRequest
func (_e *MockWorkspaceMgmtService_Expecter) CreateManagedWorkspace(namespace interface{}, req interface{}) *MockWorkspaceMgmtService_CreateManagedWorkspace_Call {
	return &MockWorkspaceMgmtService_CreateManagedWorkspace_Call{Call: _e.mock.On("CreateManagedWorkspace", namespace, req)}
}

func (_c *MockWorkspaceMgmtService_CreateManagedWorkspace_Call) Run(run func(namespace string, req types.CreateManagedWorkspaceRequest)) *MockWorkspaceMgmtService_CreateManagedWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 types.CreateManagedWorkspaceRequest
		if args[1] != nil {
			arg1 = args[1].(types.CreateManagedWorkspaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceMgmtService_CreateManagedWorkspace_Call) Return(managedWorkspaceDetail *types.ManagedWorkspaceDetail, err error) *MockWorkspaceMgmtService_CreateManagedWorkspace_Call {
	_c.Call.Return(managedWorkspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceMgmtService_CreateManagedWorkspace_Call) RunAndReturn(run func(namespace string, req types.CreateManagedWorkspaceRequest) (*types.ManagedWorkspaceDetail, error)) *MockWorkspaceMgmtService_CreateManagedWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteManagedWorkspace provides a mock function for the type MockWorkspaceMgmtService
func (_mock *MockWorkspaceMgmtService) DeleteManagedWorkspace(namespace string, name string) error {
	ret := _mock.Called(namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManagedWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(namespace, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceMgmtService_DeleteManagedWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManagedWorkspace'
type MockWorkspaceMgmtService_DeleteManagedWorkspace_Call struct {
	*mock.Call
}

// DeleteManagedWorkspace is a helper method to define mock.On call
//   - namespace string
//   - name string
func (_e *MockWorkspaceMgmtService_Expecter) DeleteManagedWorkspace(namespace interface{}, name interface{}) *MockWorkspaceMgmtService_DeleteManagedWorkspace_Call {
	return &MockWorkspaceMgmtService_DeleteManagedWorkspace_Call{Call: _e.mock.On("DeleteManagedWorkspace", namespace, name)}
}

func (_c *MockWorkspaceMgmtService_DeleteManagedWorkspace_Call) Run(run func(namespace string, name string)) *MockWorkspaceMgmtService_DeleteManagedWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceMgmtService_DeleteManagedWorkspace_Call) Return(err error) *MockWorkspaceMgmtService_DeleteManagedWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkspaceMgmtService_DeleteManagedWorkspace_Call) RunAndReturn(run func(namespace string, name string) error) *MockWorkspaceMgmtService_DeleteManagedWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GetManagedWorkspace provides a mock function for the type MockWorkspaceMgmtService
func (_mock *MockWorkspaceMgmtService) GetManagedWorkspace(namespace string, name string) (*types.ManagedWorkspaceDetail, error) {
	ret := _mock.Called(namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetManagedWorkspace")
	}

	var r0 *types.ManagedWorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*types.ManagedWorkspaceDetail, error)); ok {
		return returnFunc(namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *types.ManagedWorkspaceDetail); ok {
		r0 = returnFunc(namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ManagedWorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceMgmtService_GetManagedWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManagedWorkspace'
type MockWorkspaceMgmtService_GetManagedWorkspace_Call struct {
	*mock.Call
}

// GetManagedWorkspace is a helper method to define mock.On call
//   - namespace string
//   - name string
func (_e *MockWorkspaceMgmtService_Expecter) GetManagedWorkspace(namespace interface{}, name interface{}) *MockWorkspaceMgmtService_GetManagedWorkspace_Call {
	return &MockWorkspaceMgmtService_GetManagedWorkspace_Call{Call: _e.mock.On("GetManagedWorkspace", namespace, name)}
}

func (_c *MockWorkspaceMgmtService_GetManagedWorkspace_Call) Run(run func(namespace string, name string)) *MockWorkspaceMgmtService_GetManagedWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceMgmtService_GetManagedWorkspace_Call) Return(managedWorkspaceDetail *types.ManagedWorkspaceDetail, err error) *MockWorkspaceMgmtService_GetManagedWorkspace_Call {
	_c.Call.Return(managedWorkspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceMgmtService_GetManagedWorkspace_Call) RunAndReturn(run func(namespace string, name string) (*types.ManagedWorkspaceDetail, error)) *MockWorkspaceMgmtService_GetManagedWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ListManagedWorkspaces provides a mock function for the type MockWorkspaceMgmtService
func (_mock *MockWorkspaceMgmtService) ListManagedWorkspaces(namespace string) ([]types.ManagedWorkspaceSummary, error) {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ListManagedWorkspaces")
	}

	var r0 []types.ManagedWorkspaceSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]types.ManagedWorkspaceSummary, error)); ok {
		return returnFunc(namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []types.ManagedWorkspaceSummary); ok {
		r0 = returnFunc(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.ManagedWorkspaceSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceMgmtService_ListManagedWorkspaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManagedWorkspaces'
type MockWorkspaceMgmtService_ListManagedWorkspaces_Call struct {
	*mock.Call
}

// ListManagedWorkspaces is a helper method to define mock.On call
//   - namespace string
func (_e *MockWorkspaceMgmtService_Expecter) ListManagedWorkspaces(namespace interface{}) *MockWorkspaceMgmtService_ListManagedWorkspaces_Call {
	return &MockWorkspaceMgmtService_ListManagedWorkspaces_Call{Call: _e.mock.On("ListManagedWorkspaces", namespace)}
}

func (_c *MockWorkspaceMgmtService_ListManagedWorkspaces_Call) Run(run func(namespace string)) *MockWorkspaceMgmtService_ListManagedWorkspaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorkspaceMgmtService_ListManagedWorkspaces_Call) Return(managedWorkspaceSummarys []types.ManagedWorkspaceSummary, err error) *MockWorkspaceMgmtService_ListManagedWorkspaces_Call {
	_c.Call.Return(managedWorkspaceSummarys, err)
	return _c
}

func (_c *MockWorkspaceMgmtService_ListManagedWorkspaces_Call) RunAndReturn(run func(namespace string) ([]types.ManagedWorkspaceSummary, error)) *MockWorkspaceMgmtService_ListManagedWorkspaces_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeManagedWorkspace provides a mock function for the type MockWorkspaceMgmtService
func (_mock *MockWorkspaceMgmtService) ResumeManagedWorkspace(namespace string, name string) (*types.ManagedWorkspaceDetail, error) {
	ret := _mock.Called(namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for ResumeManagedWorkspace")
	}

	var r0 *types.ManagedWorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*types.ManagedWorkspaceDetail, error)); ok {
		return returnFunc(namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *types.ManagedWorkspaceDetail); ok {
		r0 = returnFunc(namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ManagedWorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceMgmtService_ResumeManagedWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeManagedWorkspace'
type MockWorkspaceMgmtService_ResumeManagedWorkspace_Call struct {
	*mock.Call
}

// ResumeManagedWorkspace is a helper method to define mock.On call
//   - namespace string
//   - name string
func (_e *MockWorkspaceMgmtService_Expecter) ResumeManagedWorkspace(namespace interface{}, name interface{}) *MockWorkspaceMgmtService_ResumeManagedWorkspace_Call {
	return &MockWorkspaceMgmtService_ResumeManagedWorkspace_Call{Call: _e.mock.On("ResumeManagedWorkspace", namespace, name)}
}

func (_c *MockWorkspaceMgmtService_ResumeManagedWorkspace_Call) Run(run func(namespace string, name string)) *MockWorkspaceMgmtService_ResumeManagedWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceMgmtService_ResumeManagedWorkspace_Call) Return(managedWorkspaceDetail *types.ManagedWorkspaceDetail, err error) *MockWorkspaceMgmtService_ResumeManagedWorkspace_Call {
	_c.Call.Return(managedWorkspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceMgmtService_ResumeManagedWorkspace_Call) RunAndReturn(run func(namespace string, name string) (*types.ManagedWorkspaceDetail, error)) *MockWorkspaceMgmtService_ResumeManagedWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// SuspendManagedWorkspace provides a mock function for the type MockWorkspaceMgmtService
func (_mock *MockWorkspaceMgmtService) SuspendManagedWorkspace(namespace string, name string) (*types.ManagedWorkspaceDetail, error) {
	ret := _mock.Called(namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for SuspendManagedWorkspace")
	}

	var r0 *types.ManagedWorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*types.ManagedWorkspaceDetail, error)); ok {
		return returnFunc(namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *types.ManagedWorkspaceDetail); ok {
		r0 = returnFunc(namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ManagedWorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceMgmtService_SuspendManagedWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuspendManagedWorkspace'
type MockWorkspaceMgmtService_SuspendManagedWorkspace_Call struct {
	*mock.Call
}

// SuspendManagedWorkspace is a helper method to define mock.On call
//   - namespace string
//   - name string
func (_e *MockWorkspaceMgmtService_Expecter) SuspendManagedWorkspace(namespace interface{}, name interface{}) *MockWorkspaceMgmtService_SuspendManagedWorkspace_Call {
	return &MockWorkspaceMgmtService_SuspendManagedWorkspace_Call{Call: _e.mock.On("SuspendManagedWorkspace", namespace, name)}
}

func (_c *MockWorkspaceMgmtService_SuspendManagedWorkspace_Call) Run(run func(namespace string, name string)) *MockWorkspaceMgmtService_SuspendManagedWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceMgmtService_SuspendManagedWorkspace_Call) Return(managedWorkspaceDetail *types.ManagedWorkspaceDetail, err error) *MockWorkspaceMgmtService_SuspendManagedWorkspace_Call {
	_c.Call.Return(managedWorkspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceMgmtService_SuspendManagedWorkspace_Call) RunAndReturn(run func(namespace string, name string) (*types.ManagedWorkspaceDetail, error)) *MockWorkspaceMgmtService_SuspendManagedWorkspace_Call {
	_c.Call.Return(run)
	return _c
}
