// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCUService creates a new instance of MockCUService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCUService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCUService {
	mock := &MockCUService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCUService is an autogenerated mock type for the CUService type
type MockCUService struct {
	mock.Mock
}

type MockCUService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCUService) EXPECT() *MockCUService_Expecter {
	return &MockCUService_Expecter{mock: &_m.Mock}
}

// GetCompoState provides a mock function for the type MockCUService
func (_mock *MockCUService) GetCompoState(wsPath string) (types.CompoState, error) {
	ret := _mock.Called(wsPath)

	if len(ret) == 0 {
		panic("no return value specified for GetCompoState")
	}

	var r0 types.CompoState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.CompoState, error)); ok {
		return returnFunc(wsPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.CompoState); ok {
		r0 = returnFunc(wsPath)
	} else {
		r0 = ret.Get(0).(types.CompoState)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(wsPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCUService_GetCompoState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompoState'
type MockCUService_GetCompoState_Call struct {
	*mock.Call
}

// GetCompoState is a helper method to define mock.On call
//   - wsPath string
func (_e *MockCUService_Expecter) GetCompoState(wsPath interface{}) *MockCUService_GetCompoState_Call {
	return &MockCUService_GetCompoState_Call{Call: _e.mock.On("GetCompoState", wsPath)}
}

func (_c *MockCUService_GetCompoState_Call) Run(run func(wsPath string)) *MockCUService_GetCompoState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCUService_GetCompoState_Call) Return(compoState types.CompoState, err error) *MockCUService_GetCompoState_Call {
	_c.Call.Return(compoState, err)
	return _c
}

func (_c *MockCUService_GetCompoState_Call) RunAndReturn(run func(wsPath string) (types.CompoState, error)) *MockCUService_GetCompoState_Call {
	_c.Call.Return(run)
	return _c
}
