// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockterminaladapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/terminal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewKeyStore creates a new instance of KeyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyStore {
	mock := &KeyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KeyStore is an autogenerated mock type for the KeyStore type
type KeyStore struct {
	mock.Mock
}

type KeyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyStore) EXPECT() *KeyStore_Expecter {
	return &KeyStore_Expecter{mock: &_m.Mock}
}

// DeleteKey provides a mock function for the type KeyStore
func (_mock *KeyStore) DeleteKey(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyStore_DeleteKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKey'
type KeyStore_DeleteKey_Call struct {
	*mock.Call
}

// DeleteKey is a helper method to define mock.On call
//   - name string
func (_e *KeyStore_Expecter) DeleteKey(name interface{}) *KeyStore_DeleteKey_Call {
	return &KeyStore_DeleteKey_Call{Call: _e.mock.On("DeleteKey", name)}
}

func (_c *KeyStore_DeleteKey_Call) Run(run func(name string)) *KeyStore_DeleteKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyStore_DeleteKey_Call) Return(err error) *KeyStore_DeleteKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyStore_DeleteKey_Call) RunAndReturn(run func(name string) error) *KeyStore_DeleteKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetKey provides a mock function for the type KeyStore
func (_mock *KeyStore) GetKey(name string) (types.SSHKey, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetKey")
	}

	var r0 types.SSHKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.SSHKey, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.SSHKey); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(types.SSHKey)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyStore_GetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKey'
type KeyStore_GetKey_Call struct {
	*mock.Call
}

// GetKey is a helper method to define mock.On call
//   - name string
func (_e *KeyStore_Expecter) GetKey(name interface{}) *KeyStore_GetKey_Call {
	return &KeyStore_GetKey_Call{Call: _e.mock.On("GetKey", name)}
}

func (_c *KeyStore_GetKey_Call) Run(run func(name string)) *KeyStore_GetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyStore_GetKey_Call) Return(sSHKey types.SSHKey, err error) *KeyStore_GetKey_Call {
	_c.Call.Return(sSHKey, err)
	return _c
}

func (_c *KeyStore_GetKey_Call) RunAndReturn(run func(name string) (types.SSHKey, error)) *KeyStore_GetKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetParams provides a mock function for the type KeyStore
func (_mock *KeyStore) GetParams() (map[string]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParams")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyStore_GetParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParams'
type KeyStore_GetParams_Call struct {
	*mock.Call
}

// GetParams is a helper method to define mock.On call
func (_e *KeyStore_Expecter) GetParams() *KeyStore_GetParams_Call {
	return &KeyStore_GetParams_Call{Call: _e.mock.On("GetParams")}
}

func (_c *KeyStore_GetParams_Call) Run(run func()) *KeyStore_GetParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KeyStore_GetParams_Call) Return(stringToString map[string]string, err error) *KeyStore_GetParams_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *KeyStore_GetParams_Call) RunAndReturn(run func() (map[string]string, error)) *KeyStore_GetParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListEndpoints provides a mock function for the type KeyStore
func (_mock *KeyStore) ListEndpoints() ([]types.TerminalEndpoint, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListEndpoints")
	}

	var r0 []types.TerminalEndpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]types.TerminalEndpoint, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []types.TerminalEndpoint); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.TerminalEndpoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyStore_ListEndpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEndpoints'
type KeyStore_ListEndpoints_Call struct {
	*mock.Call
}

// ListEndpoints is a helper method to define mock.On call
func (_e *KeyStore_Expecter) ListEndpoints() *KeyStore_ListEndpoints_Call {
	return &KeyStore_ListEndpoints_Call{Call: _e.mock.On("ListEndpoints")}
}

func (_c *KeyStore_ListEndpoints_Call) Run(run func()) *KeyStore_ListEndpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KeyStore_ListEndpoints_Call) Return(terminalEndpoints []types.TerminalEndpoint, err error) *KeyStore_ListEndpoints_Call {
	_c.Call.Return(terminalEndpoints, err)
	return _c
}

func (_c *KeyStore_ListEndpoints_Call) RunAndReturn(run func() ([]types.TerminalEndpoint, error)) *KeyStore_ListEndpoints_Call {
	_c.Call.Return(run)
	return _c
}

// ListHosts provides a mock function for the type KeyStore
func (_mock *KeyStore) ListHosts() ([]types.KnownHost, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListHosts")
	}

	var r0 []types.KnownHost
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]types.KnownHost, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []types.KnownHost); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.KnownHost)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyStore_ListHosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHosts'
type KeyStore_ListHosts_Call struct {
	*mock.Call
}

// ListHosts is a helper method to define mock.On call
func (_e *KeyStore_Expecter) ListHosts() *KeyStore_ListHosts_Call {
	return &KeyStore_ListHosts_Call{Call: _e.mock.On("ListHosts")}
}

func (_c *KeyStore_ListHosts_Call) Run(run func()) *KeyStore_ListHosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KeyStore_ListHosts_Call) Return(knownHosts []types.KnownHost, err error) *KeyStore_ListHosts_Call {
	_c.Call.Return(knownHosts, err)
	return _c
}

func (_c *KeyStore_ListHosts_Call) RunAndReturn(run func() ([]types.KnownHost, error)) *KeyStore_ListHosts_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeys provides a mock function for the type KeyStore
func (_mock *KeyStore) ListKeys() ([]types.SSHKey, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListKeys")
	}

	var r0 []types.SSHKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]types.SSHKey, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []types.SSHKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.SSHKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyStore_ListKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeys'
type KeyStore_ListKeys_Call struct {
	*mock.Call
}

// ListKeys is a helper method to define mock.On call
func (_e *KeyStore_Expecter) ListKeys() *KeyStore_ListKeys_Call {
	return &KeyStore_ListKeys_Call{Call: _e.mock.On("ListKeys")}
}

func (_c *KeyStore_ListKeys_Call) Run(run func()) *KeyStore_ListKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KeyStore_ListKeys_Call) Return(sSHKeys []types.SSHKey, err error) *KeyStore_ListKeys_Call {
	_c.Call.Return(sSHKeys, err)
	return _c
}

func (_c *KeyStore_ListKeys_Call) RunAndReturn(run func() ([]types.SSHKey, error)) *KeyStore_ListKeys_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEndpoint provides a mock function for the type KeyStore
func (_mock *KeyStore) SaveEndpoint(ep types.TerminalEndpoint) error {
	ret := _mock.Called(ep)

	if len(ret) == 0 {
		panic("no return value specified for SaveEndpoint")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.TerminalEndpoint) error); ok {
		r0 = returnFunc(ep)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyStore_SaveEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEndpoint'
type KeyStore_SaveEndpoint_Call struct {
	*mock.Call
}

// SaveEndpoint is a helper method to define mock.On call
//   - ep types.TerminalEndpoint
func (_e *KeyStore_Expecter) SaveEndpoint(ep interface{}) *KeyStore_SaveEndpoint_Call {
	return &KeyStore_SaveEndpoint_Call{Call: _e.mock.On("SaveEndpoint", ep)}
}

func (_c *KeyStore_SaveEndpoint_Call) Run(run func(ep types.TerminalEndpoint)) *KeyStore_SaveEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.TerminalEndpoint
		if args[0] != nil {
			arg0 = args[0].(types.TerminalEndpoint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyStore_SaveEndpoint_Call) Return(err error) *KeyStore_SaveEndpoint_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyStore_SaveEndpoint_Call) RunAndReturn(run func(ep types.TerminalEndpoint) error) *KeyStore_SaveEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// SaveHost provides a mock function for the type KeyStore
func (_mock *KeyStore) SaveHost(host types.KnownHost) error {
	ret := _mock.Called(host)

	if len(ret) == 0 {
		panic("no return value specified for SaveHost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.KnownHost) error); ok {
		r0 = returnFunc(host)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyStore_SaveHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveHost'
type KeyStore_SaveHost_Call struct {
	*mock.Call
}

// SaveHost is a helper method to define mock.On call
//   - host types.KnownHost
func (_e *KeyStore_Expecter) SaveHost(host interface{}) *KeyStore_SaveHost_Call {
	return &KeyStore_SaveHost_Call{Call: _e.mock.On("SaveHost", host)}
}

func (_c *KeyStore_SaveHost_Call) Run(run func(host types.KnownHost)) *KeyStore_SaveHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.KnownHost
		if args[0] != nil {
			arg0 = args[0].(types.KnownHost)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyStore_SaveHost_Call) Return(err error) *KeyStore_SaveHost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyStore_SaveHost_Call) RunAndReturn(run func(host types.KnownHost) error) *KeyStore_SaveHost_Call {
	_c.Call.Return(run)
	return _c
}

// SaveKey provides a mock function for the type KeyStore
func (_mock *KeyStore) SaveKey(key types.SSHKey) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for SaveKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.SSHKey) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyStore_SaveKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveKey'
type KeyStore_SaveKey_Call struct {
	*mock.Call
}

// SaveKey is a helper method to define mock.On call
//   - key types.SSHKey
func (_e *KeyStore_Expecter) SaveKey(key interface{}) *KeyStore_SaveKey_Call {
	return &KeyStore_SaveKey_Call{Call: _e.mock.On("SaveKey", key)}
}

func (_c *KeyStore_SaveKey_Call) Run(run func(key types.SSHKey)) *KeyStore_SaveKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.SSHKey
		if args[0] != nil {
			arg0 = args[0].(types.SSHKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyStore_SaveKey_Call) Return(err error) *KeyStore_SaveKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyStore_SaveKey_Call) RunAndReturn(run func(key types.SSHKey) error) *KeyStore_SaveKey_Call {
	_c.Call.Return(run)
	return _c
}

// SaveParams provides a mock function for the type KeyStore
func (_mock *KeyStore) SaveParams(params map[string]string) error {
	ret := _mock.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for SaveParams")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = returnFunc(params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyStore_SaveParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveParams'
type KeyStore_SaveParams_Call struct {
	*mock.Call
}

// SaveParams is a helper method to define mock.On call
//   - params map[string]string
func (_e *KeyStore_Expecter) SaveParams(params interface{}) *KeyStore_SaveParams_Call {
	return &KeyStore_SaveParams_Call{Call: _e.mock.On("SaveParams", params)}
}

func (_c *KeyStore_SaveParams_Call) Run(run func(params map[string]string)) *KeyStore_SaveParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyStore_SaveParams_Call) Return(err error) *KeyStore_SaveParams_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyStore_SaveParams_Call) RunAndReturn(run func(params map[string]string) error) *KeyStore_SaveParams_Call {
	_c.Call.Return(run)
	return _c
}
