// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockterminaladapter

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTerminalIO creates a new instance of TerminalIO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerminalIO(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerminalIO {
	mock := &TerminalIO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TerminalIO is an autogenerated mock type for the TerminalIO type
type TerminalIO struct {
	mock.Mock
}

type TerminalIO_Expecter struct {
	mock *mock.Mock
}

func (_m *TerminalIO) EXPECT() *TerminalIO_Expecter {
	return &TerminalIO_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type TerminalIO
func (_mock *TerminalIO) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TerminalIO_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type TerminalIO_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *TerminalIO_Expecter) Close() *TerminalIO_Close_Call {
	return &TerminalIO_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *TerminalIO_Close_Call) Run(run func()) *TerminalIO_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TerminalIO_Close_Call) Return(err error) *TerminalIO_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TerminalIO_Close_Call) RunAndReturn(run func() error) *TerminalIO_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Cols provides a mock function for the type TerminalIO
func (_mock *TerminalIO) Cols() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cols")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// TerminalIO_Cols_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cols'
type TerminalIO_Cols_Call struct {
	*mock.Call
}

// Cols is a helper method to define mock.On call
func (_e *TerminalIO_Expecter) Cols() *TerminalIO_Cols_Call {
	return &TerminalIO_Cols_Call{Call: _e.mock.On("Cols")}
}

func (_c *TerminalIO_Cols_Call) Run(run func()) *TerminalIO_Cols_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TerminalIO_Cols_Call) Return(n int) *TerminalIO_Cols_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *TerminalIO_Cols_Call) RunAndReturn(run func() int) *TerminalIO_Cols_Call {
	_c.Call.Return(run)
	return _c
}

// OnResize provides a mock function for the type TerminalIO
func (_mock *TerminalIO) OnResize(fn func(cols int, rows int)) {
	_mock.Called(fn)
	return
}

// TerminalIO_OnResize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnResize'
type TerminalIO_OnResize_Call struct {
	*mock.Call
}

// OnResize is a helper method to define mock.On call
//   - fn func(cols int, rows int)
func (_e *TerminalIO_Expecter) OnResize(fn interface{}) *TerminalIO_OnResize_Call {
	return &TerminalIO_OnResize_Call{Call: _e.mock.On("OnResize", fn)}
}

func (_c *TerminalIO_OnResize_Call) Run(run func(fn func(cols int, rows int))) *TerminalIO_OnResize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(cols int, rows int)
		if args[0] != nil {
			arg0 = args[0].(func(cols int, rows int))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TerminalIO_OnResize_Call) Return() *TerminalIO_OnResize_Call {
	_c.Call.Return()
	return _c
}

func (_c *TerminalIO_OnResize_Call) RunAndReturn(run func(fn func(cols int, rows int))) *TerminalIO_OnResize_Call {
	_c.Run(run)
	return _c
}

// Read provides a mock function for the type TerminalIO
func (_mock *TerminalIO) Read(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TerminalIO_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type TerminalIO_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - b []byte
func (_e *TerminalIO_Expecter) Read(b interface{}) *TerminalIO_Read_Call {
	return &TerminalIO_Read_Call{Call: _e.mock.On("Read", b)}
}

func (_c *TerminalIO_Read_Call) Run(run func(b []byte)) *TerminalIO_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TerminalIO_Read_Call) Return(n int, err error) *TerminalIO_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *TerminalIO_Read_Call) RunAndReturn(run func(b []byte) (int, error)) *TerminalIO_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Rows provides a mock function for the type TerminalIO
func (_mock *TerminalIO) Rows() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rows")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// TerminalIO_Rows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rows'
type TerminalIO_Rows_Call struct {
	*mock.Call
}

// Rows is a helper method to define mock.On call
func (_e *TerminalIO_Expecter) Rows() *TerminalIO_Rows_Call {
	return &TerminalIO_Rows_Call{Call: _e.mock.On("Rows")}
}

func (_c *TerminalIO_Rows_Call) Run(run func()) *TerminalIO_Rows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TerminalIO_Rows_Call) Return(n int) *TerminalIO_Rows_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *TerminalIO_Rows_Call) RunAndReturn(run func() int) *TerminalIO_Rows_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type TerminalIO
func (_mock *TerminalIO) Write(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TerminalIO_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type TerminalIO_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - b []byte
func (_e *TerminalIO_Expecter) Write(b interface{}) *TerminalIO_Write_Call {
	return &TerminalIO_Write_Call{Call: _e.mock.On("Write", b)}
}

func (_c *TerminalIO_Write_Call) Run(run func(b []byte)) *TerminalIO_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TerminalIO_Write_Call) Return(n int, err error) *TerminalIO_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *TerminalIO_Write_Call) RunAndReturn(run func(b []byte) (int, error)) *TerminalIO_Write_Call {
	_c.Call.Return(run)
	return _c
}
