// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockterminaladapter

import (
	mock "github.com/stretchr/testify/mock"
)

// NewKeyRegistrar creates a new instance of KeyRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyRegistrar {
	mock := &KeyRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KeyRegistrar is an autogenerated mock type for the KeyRegistrar type
type KeyRegistrar struct {
	mock.Mock
}

type KeyRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyRegistrar) EXPECT() *KeyRegistrar_Expecter {
	return &KeyRegistrar_Expecter{mock: &_m.Mock}
}

// RegisterKey provides a mock function for the type KeyRegistrar
func (_mock *KeyRegistrar) RegisterKey(workspace string, publicKey string) error {
	ret := _mock.Called(workspace, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(workspace, publicKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyRegistrar_RegisterKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterKey'
type KeyRegistrar_RegisterKey_Call struct {
	*mock.Call
}

// RegisterKey is a helper method to define mock.On call
//   - workspace string
//   - publicKey string
func (_e *KeyRegistrar_Expecter) RegisterKey(workspace interface{}, publicKey interface{}) *KeyRegistrar_RegisterKey_Call {
	return &KeyRegistrar_RegisterKey_Call{Call: _e.mock.On("RegisterKey", workspace, publicKey)}
}

func (_c *KeyRegistrar_RegisterKey_Call) Run(run func(workspace string, publicKey string)) *KeyRegistrar_RegisterKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KeyRegistrar_RegisterKey_Call) Return(err error) *KeyRegistrar_RegisterKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyRegistrar_RegisterKey_Call) RunAndReturn(run func(workspace string, publicKey string) error) *KeyRegistrar_RegisterKey_Call {
	_c.Call.Return(run)
	return _c
}
