// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockterminaladapter

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTerminalIO creates a new instance of MockTerminalIO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTerminalIO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTerminalIO {
	mock := &MockTerminalIO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTerminalIO is an autogenerated mock type for the TerminalIO type
type MockTerminalIO struct {
	mock.Mock
}

type MockTerminalIO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTerminalIO) EXPECT() *MockTerminalIO_Expecter {
	return &MockTerminalIO_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockTerminalIO
func (_mock *MockTerminalIO) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTerminalIO_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTerminalIO_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockTerminalIO_Expecter) Close() *MockTerminalIO_Close_Call {
	return &MockTerminalIO_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockTerminalIO_Close_Call) Run(run func()) *MockTerminalIO_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTerminalIO_Close_Call) Return(err error) *MockTerminalIO_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTerminalIO_Close_Call) RunAndReturn(run func() error) *MockTerminalIO_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Cols provides a mock function for the type MockTerminalIO
func (_mock *MockTerminalIO) Cols() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cols")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockTerminalIO_Cols_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cols'
type MockTerminalIO_Cols_Call struct {
	*mock.Call
}

// Cols is a helper method to define mock.On call
func (_e *MockTerminalIO_Expecter) Cols() *MockTerminalIO_Cols_Call {
	return &MockTerminalIO_Cols_Call{Call: _e.mock.On("Cols")}
}

func (_c *MockTerminalIO_Cols_Call) Run(run func()) *MockTerminalIO_Cols_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTerminalIO_Cols_Call) Return(n int) *MockTerminalIO_Cols_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTerminalIO_Cols_Call) RunAndReturn(run func() int) *MockTerminalIO_Cols_Call {
	_c.Call.Return(run)
	return _c
}

// OnResize provides a mock function for the type MockTerminalIO
func (_mock *MockTerminalIO) OnResize(fn func(cols int, rows int)) {
	_mock.Called(fn)
	return
}

// MockTerminalIO_OnResize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnResize'
type MockTerminalIO_OnResize_Call struct {
	*mock.Call
}

// OnResize is a helper method to define mock.On call
//   - fn func(cols int, rows int)
func (_e *MockTerminalIO_Expecter) OnResize(fn interface{}) *MockTerminalIO_OnResize_Call {
	return &MockTerminalIO_OnResize_Call{Call: _e.mock.On("OnResize", fn)}
}

func (_c *MockTerminalIO_OnResize_Call) Run(run func(fn func(cols int, rows int))) *MockTerminalIO_OnResize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(cols int, rows int)
		if args[0] != nil {
			arg0 = args[0].(func(cols int, rows int))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTerminalIO_OnResize_Call) Return() *MockTerminalIO_OnResize_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTerminalIO_OnResize_Call) RunAndReturn(run func(fn func(cols int, rows int))) *MockTerminalIO_OnResize_Call {
	_c.Run(run)
	return _c
}

// Read provides a mock function for the type MockTerminalIO
func (_mock *MockTerminalIO) Read(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTerminalIO_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockTerminalIO_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - b []byte
func (_e *MockTerminalIO_Expecter) Read(b interface{}) *MockTerminalIO_Read_Call {
	return &MockTerminalIO_Read_Call{Call: _e.mock.On("Read", b)}
}

func (_c *MockTerminalIO_Read_Call) Run(run func(b []byte)) *MockTerminalIO_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTerminalIO_Read_Call) Return(n int, err error) *MockTerminalIO_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTerminalIO_Read_Call) RunAndReturn(run func(b []byte) (int, error)) *MockTerminalIO_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Rows provides a mock function for the type MockTerminalIO
func (_mock *MockTerminalIO) Rows() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rows")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockTerminalIO_Rows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rows'
type MockTerminalIO_Rows_Call struct {
	*mock.Call
}

// Rows is a helper method to define mock.On call
func (_e *MockTerminalIO_Expecter) Rows() *MockTerminalIO_Rows_Call {
	return &MockTerminalIO_Rows_Call{Call: _e.mock.On("Rows")}
}

func (_c *MockTerminalIO_Rows_Call) Run(run func()) *MockTerminalIO_Rows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTerminalIO_Rows_Call) Return(n int) *MockTerminalIO_Rows_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTerminalIO_Rows_Call) RunAndReturn(run func() int) *MockTerminalIO_Rows_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockTerminalIO
func (_mock *MockTerminalIO) Write(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTerminalIO_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockTerminalIO_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - b []byte
func (_e *MockTerminalIO_Expecter) Write(b interface{}) *MockTerminalIO_Write_Call {
	return &MockTerminalIO_Write_Call{Call: _e.mock.On("Write", b)}
}

func (_c *MockTerminalIO_Write_Call) Run(run func(b []byte)) *MockTerminalIO_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTerminalIO_Write_Call) Return(n int, err error) *MockTerminalIO_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTerminalIO_Write_Call) RunAndReturn(run func(b []byte) (int, error)) *MockTerminalIO_Write_Call {
	_c.Call.Return(run)
	return _c
}
