// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockterminaladapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/terminal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkspaceInfoClient creates a new instance of MockWorkspaceInfoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceInfoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceInfoClient {
	mock := &MockWorkspaceInfoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkspaceInfoClient is an autogenerated mock type for the WorkspaceInfoClient type
type MockWorkspaceInfoClient struct {
	mock.Mock
}

type MockWorkspaceInfoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceInfoClient) EXPECT() *MockWorkspaceInfoClient_Expecter {
	return &MockWorkspaceInfoClient_Expecter{mock: &_m.Mock}
}

// GetInfo provides a mock function for the type MockWorkspaceInfoClient
func (_mock *MockWorkspaceInfoClient) GetInfo(workspace string) (types.WorkspaceInfo, error) {
	ret := _mock.Called(workspace)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 types.WorkspaceInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.WorkspaceInfo, error)); ok {
		return returnFunc(workspace)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.WorkspaceInfo); ok {
		r0 = returnFunc(workspace)
	} else {
		r0 = ret.Get(0).(types.WorkspaceInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(workspace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceInfoClient_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type MockWorkspaceInfoClient_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
//   - workspace string
func (_e *MockWorkspaceInfoClient_Expecter) GetInfo(workspace interface{}) *MockWorkspaceInfoClient_GetInfo_Call {
	return &MockWorkspaceInfoClient_GetInfo_Call{Call: _e.mock.On("GetInfo", workspace)}
}

func (_c *MockWorkspaceInfoClient_GetInfo_Call) Run(run func(workspace string)) *MockWorkspaceInfoClient_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorkspaceInfoClient_GetInfo_Call) Return(workspaceInfo types.WorkspaceInfo, err error) *MockWorkspaceInfoClient_GetInfo_Call {
	_c.Call.Return(workspaceInfo, err)
	return _c
}

func (_c *MockWorkspaceInfoClient_GetInfo_Call) RunAndReturn(run func(workspace string) (types.WorkspaceInfo, error)) *MockWorkspaceInfoClient_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}
