// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockterminaladapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/terminal/adapter"
	"github.com/alexandremahdhaoui/forge-ui/internal/terminal/types"
	mock "github.com/stretchr/testify/mock"
	"golang.org/x/crypto/ssh"
)

// NewMockSSHClient creates a new instance of MockSSHClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSHClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSHClient {
	mock := &MockSSHClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSSHClient is an autogenerated mock type for the SSHClient type
type MockSSHClient struct {
	mock.Mock
}

type MockSSHClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSHClient) EXPECT() *MockSSHClient_Expecter {
	return &MockSSHClient_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockSSHClient
func (_mock *MockSSHClient) Connect(cfg types.SSHSessionConfig, signers []ssh.Signer, hostCb ssh.HostKeyCallback) (adapter.SSHSession, error) {
	ret := _mock.Called(cfg, signers, hostCb)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 adapter.SSHSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(types.SSHSessionConfig, []ssh.Signer, ssh.HostKeyCallback) (adapter.SSHSession, error)); ok {
		return returnFunc(cfg, signers, hostCb)
	}
	if returnFunc, ok := ret.Get(0).(func(types.SSHSessionConfig, []ssh.Signer, ssh.HostKeyCallback) adapter.SSHSession); ok {
		r0 = returnFunc(cfg, signers, hostCb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.SSHSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(types.SSHSessionConfig, []ssh.Signer, ssh.HostKeyCallback) error); ok {
		r1 = returnFunc(cfg, signers, hostCb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSSHClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockSSHClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - cfg types.SSHSessionConfig
//   - signers []ssh.Signer
//   - hostCb ssh.HostKeyCallback
func (_e *MockSSHClient_Expecter) Connect(cfg interface{}, signers interface{}, hostCb interface{}) *MockSSHClient_Connect_Call {
	return &MockSSHClient_Connect_Call{Call: _e.mock.On("Connect", cfg, signers, hostCb)}
}

func (_c *MockSSHClient_Connect_Call) Run(run func(cfg types.SSHSessionConfig, signers []ssh.Signer, hostCb ssh.HostKeyCallback)) *MockSSHClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.SSHSessionConfig
		if args[0] != nil {
			arg0 = args[0].(types.SSHSessionConfig)
		}
		var arg1 []ssh.Signer
		if args[1] != nil {
			arg1 = args[1].([]ssh.Signer)
		}
		var arg2 ssh.HostKeyCallback
		if args[2] != nil {
			arg2 = args[2].(ssh.HostKeyCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSSHClient_Connect_Call) Return(sSHSession adapter.SSHSession, err error) *MockSSHClient_Connect_Call {
	_c.Call.Return(sSHSession, err)
	return _c
}

func (_c *MockSSHClient_Connect_Call) RunAndReturn(run func(cfg types.SSHSessionConfig, signers []ssh.Signer, hostCb ssh.HostKeyCallback) (adapter.SSHSession, error)) *MockSSHClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}
