// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockterminaladapter

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSSHSession creates a new instance of MockSSHSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSHSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSHSession {
	mock := &MockSSHSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSSHSession is an autogenerated mock type for the SSHSession type
type MockSSHSession struct {
	mock.Mock
}

type MockSSHSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSHSession) EXPECT() *MockSSHSession_Expecter {
	return &MockSSHSession_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockSSHSession
func (_mock *MockSSHSession) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSSHSession_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSSHSession_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSSHSession_Expecter) Close() *MockSSHSession_Close_Call {
	return &MockSSHSession_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSSHSession_Close_Call) Run(run func()) *MockSSHSession_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSSHSession_Close_Call) Return(err error) *MockSSHSession_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSSHSession_Close_Call) RunAndReturn(run func() error) *MockSSHSession_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Resize provides a mock function for the type MockSSHSession
func (_mock *MockSSHSession) Resize(cols int, rows int) error {
	ret := _mock.Called(cols, rows)

	if len(ret) == 0 {
		panic("no return value specified for Resize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = returnFunc(cols, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSSHSession_Resize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resize'
type MockSSHSession_Resize_Call struct {
	*mock.Call
}

// Resize is a helper method to define mock.On call
//   - cols int
//   - rows int
func (_e *MockSSHSession_Expecter) Resize(cols interface{}, rows interface{}) *MockSSHSession_Resize_Call {
	return &MockSSHSession_Resize_Call{Call: _e.mock.On("Resize", cols, rows)}
}

func (_c *MockSSHSession_Resize_Call) Run(run func(cols int, rows int)) *MockSSHSession_Resize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSSHSession_Resize_Call) Return(err error) *MockSSHSession_Resize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSSHSession_Resize_Call) RunAndReturn(run func(cols int, rows int) error) *MockSSHSession_Resize_Call {
	_c.Call.Return(run)
	return _c
}

// Stdin provides a mock function for the type MockSSHSession
func (_mock *MockSSHSession) Stdin() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdin")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockSSHSession_Stdin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdin'
type MockSSHSession_Stdin_Call struct {
	*mock.Call
}

// Stdin is a helper method to define mock.On call
func (_e *MockSSHSession_Expecter) Stdin() *MockSSHSession_Stdin_Call {
	return &MockSSHSession_Stdin_Call{Call: _e.mock.On("Stdin")}
}

func (_c *MockSSHSession_Stdin_Call) Run(run func()) *MockSSHSession_Stdin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSSHSession_Stdin_Call) Return(writer io.Writer) *MockSSHSession_Stdin_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockSSHSession_Stdin_Call) RunAndReturn(run func() io.Writer) *MockSSHSession_Stdin_Call {
	_c.Call.Return(run)
	return _c
}

// Stdout provides a mock function for the type MockSSHSession
func (_mock *MockSSHSession) Stdout() io.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdout")
	}

	var r0 io.Reader
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	return r0
}

// MockSSHSession_Stdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdout'
type MockSSHSession_Stdout_Call struct {
	*mock.Call
}

// Stdout is a helper method to define mock.On call
func (_e *MockSSHSession_Expecter) Stdout() *MockSSHSession_Stdout_Call {
	return &MockSSHSession_Stdout_Call{Call: _e.mock.On("Stdout")}
}

func (_c *MockSSHSession_Stdout_Call) Run(run func()) *MockSSHSession_Stdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSSHSession_Stdout_Call) Return(reader io.Reader) *MockSSHSession_Stdout_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *MockSSHSession_Stdout_Call) RunAndReturn(run func() io.Reader) *MockSSHSession_Stdout_Call {
	_c.Call.Return(run)
	return _c
}
