apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "forge-workspace.fullname" . }}
  labels:
    {{- include "forge-workspace.labels" . | nindent 4 }}
data:
  sshd_config: |
    Port 22
    PasswordAuthentication no
    PubkeyAuthentication yes
    PermitRootLogin no
    AllowUsers {{ .Values.config.username }}
    AuthorizedKeysFile /home/%u/.ssh/authorized_keys
    Subsystem sftp /usr/lib/ssh/sftp-server
    AuthorizedKeysCommand /usr/local/bin/get-authorized-keys %u
    AuthorizedKeysCommandUser nobody
  authorized_keys: |
    {{- range .Values.ssh.authorizedKeys }}
    {{ . }}
    {{- end }}
