// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewPortfolioDiscovery creates a new instance of PortfolioDiscovery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortfolioDiscovery(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortfolioDiscovery {
	mock := &PortfolioDiscovery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PortfolioDiscovery is an autogenerated mock type for the PortfolioDiscovery type
type PortfolioDiscovery struct {
	mock.Mock
}

type PortfolioDiscovery_Expecter struct {
	mock *mock.Mock
}

func (_m *PortfolioDiscovery) EXPECT() *PortfolioDiscovery_Expecter {
	return &PortfolioDiscovery_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type PortfolioDiscovery
func (_mock *PortfolioDiscovery) Get(baseDir string, name string) (types.PortfolioPageData, error) {
	ret := _mock.Called(baseDir, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 types.PortfolioPageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (types.PortfolioPageData, error)); ok {
		return returnFunc(baseDir, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) types.PortfolioPageData); ok {
		r0 = returnFunc(baseDir, name)
	} else {
		r0 = ret.Get(0).(types.PortfolioPageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(baseDir, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PortfolioDiscovery_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PortfolioDiscovery_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - baseDir string
//   - name string
func (_e *PortfolioDiscovery_Expecter) Get(baseDir interface{}, name interface{}) *PortfolioDiscovery_Get_Call {
	return &PortfolioDiscovery_Get_Call{Call: _e.mock.On("Get", baseDir, name)}
}

func (_c *PortfolioDiscovery_Get_Call) Run(run func(baseDir string, name string)) *PortfolioDiscovery_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PortfolioDiscovery_Get_Call) Return(portfolioPageData types.PortfolioPageData, err error) *PortfolioDiscovery_Get_Call {
	_c.Call.Return(portfolioPageData, err)
	return _c
}

func (_c *PortfolioDiscovery_Get_Call) RunAndReturn(run func(baseDir string, name string) (types.PortfolioPageData, error)) *PortfolioDiscovery_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type PortfolioDiscovery
func (_mock *PortfolioDiscovery) List(baseDir string) ([]types.PortfolioSummary, error) {
	ret := _mock.Called(baseDir)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []types.PortfolioSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]types.PortfolioSummary, error)); ok {
		return returnFunc(baseDir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []types.PortfolioSummary); ok {
		r0 = returnFunc(baseDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.PortfolioSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(baseDir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PortfolioDiscovery_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PortfolioDiscovery_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - baseDir string
func (_e *PortfolioDiscovery_Expecter) List(baseDir interface{}) *PortfolioDiscovery_List_Call {
	return &PortfolioDiscovery_List_Call{Call: _e.mock.On("List", baseDir)}
}

func (_c *PortfolioDiscovery_List_Call) Run(run func(baseDir string)) *PortfolioDiscovery_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PortfolioDiscovery_List_Call) Return(portfolioSummarys []types.PortfolioSummary, err error) *PortfolioDiscovery_List_Call {
	_c.Call.Return(portfolioSummarys, err)
	return _c
}

func (_c *PortfolioDiscovery_List_Call) RunAndReturn(run func(baseDir string) ([]types.PortfolioSummary, error)) *PortfolioDiscovery_List_Call {
	_c.Call.Return(run)
	return _c
}
