// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMetaPlanLoader creates a new instance of MetaPlanLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetaPlanLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetaPlanLoader {
	mock := &MetaPlanLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MetaPlanLoader is an autogenerated mock type for the MetaPlanLoader type
type MetaPlanLoader struct {
	mock.Mock
}

type MetaPlanLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MetaPlanLoader) EXPECT() *MetaPlanLoader_Expecter {
	return &MetaPlanLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MetaPlanLoader
func (_mock *MetaPlanLoader) Load(path string) (types.MetaPlan, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 types.MetaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.MetaPlan, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.MetaPlan); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(types.MetaPlan)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetaPlanLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MetaPlanLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - path string
func (_e *MetaPlanLoader_Expecter) Load(path interface{}) *MetaPlanLoader_Load_Call {
	return &MetaPlanLoader_Load_Call{Call: _e.mock.On("Load", path)}
}

func (_c *MetaPlanLoader_Load_Call) Run(run func(path string)) *MetaPlanLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MetaPlanLoader_Load_Call) Return(metaPlan types.MetaPlan, err error) *MetaPlanLoader_Load_Call {
	_c.Call.Return(metaPlan, err)
	return _c
}

func (_c *MetaPlanLoader_Load_Call) RunAndReturn(run func(path string) (types.MetaPlan, error)) *MetaPlanLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}

// LoadAll provides a mock function for the type MetaPlanLoader
func (_mock *MetaPlanLoader) LoadAll(wsPath string) ([]types.MetaPlan, error) {
	ret := _mock.Called(wsPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 []types.MetaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]types.MetaPlan, error)); ok {
		return returnFunc(wsPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []types.MetaPlan); ok {
		r0 = returnFunc(wsPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.MetaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(wsPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetaPlanLoader_LoadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadAll'
type MetaPlanLoader_LoadAll_Call struct {
	*mock.Call
}

// LoadAll is a helper method to define mock.On call
//   - wsPath string
func (_e *MetaPlanLoader_Expecter) LoadAll(wsPath interface{}) *MetaPlanLoader_LoadAll_Call {
	return &MetaPlanLoader_LoadAll_Call{Call: _e.mock.On("LoadAll", wsPath)}
}

func (_c *MetaPlanLoader_LoadAll_Call) Run(run func(wsPath string)) *MetaPlanLoader_LoadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MetaPlanLoader_LoadAll_Call) Return(metaPlans []types.MetaPlan, err error) *MetaPlanLoader_LoadAll_Call {
	_c.Call.Return(metaPlans, err)
	return _c
}

func (_c *MetaPlanLoader_LoadAll_Call) RunAndReturn(run func(wsPath string) ([]types.MetaPlan, error)) *MetaPlanLoader_LoadAll_Call {
	_c.Call.Return(run)
	return _c
}
