// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

type Cache_Expecter struct {
	mock *mock.Mock
}

func (_m *Cache) EXPECT() *Cache_Expecter {
	return &Cache_Expecter{mock: &_m.Mock}
}

// GetRepoOverview provides a mock function for the type Cache
func (_mock *Cache) GetRepoOverview(workspace string, repo string) (types.RepoOverview, bool) {
	ret := _mock.Called(workspace, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoOverview")
	}

	var r0 types.RepoOverview
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) (types.RepoOverview, bool)); ok {
		return returnFunc(workspace, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) types.RepoOverview); ok {
		r0 = returnFunc(workspace, repo)
	} else {
		r0 = ret.Get(0).(types.RepoOverview)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = returnFunc(workspace, repo)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Cache_GetRepoOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoOverview'
type Cache_GetRepoOverview_Call struct {
	*mock.Call
}

// GetRepoOverview is a helper method to define mock.On call
//   - workspace string
//   - repo string
func (_e *Cache_Expecter) GetRepoOverview(workspace interface{}, repo interface{}) *Cache_GetRepoOverview_Call {
	return &Cache_GetRepoOverview_Call{Call: _e.mock.On("GetRepoOverview", workspace, repo)}
}

func (_c *Cache_GetRepoOverview_Call) Run(run func(workspace string, repo string)) *Cache_GetRepoOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetRepoOverview_Call) Return(repoOverview types.RepoOverview, b bool) *Cache_GetRepoOverview_Call {
	_c.Call.Return(repoOverview, b)
	return _c
}

func (_c *Cache_GetRepoOverview_Call) RunAndReturn(run func(workspace string, repo string) (types.RepoOverview, bool)) *Cache_GetRepoOverview_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoSummary provides a mock function for the type Cache
func (_mock *Cache) GetRepoSummary(workspace string, repo string) (types.RepoSummary, bool) {
	ret := _mock.Called(workspace, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoSummary")
	}

	var r0 types.RepoSummary
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) (types.RepoSummary, bool)); ok {
		return returnFunc(workspace, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) types.RepoSummary); ok {
		r0 = returnFunc(workspace, repo)
	} else {
		r0 = ret.Get(0).(types.RepoSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = returnFunc(workspace, repo)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Cache_GetRepoSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoSummary'
type Cache_GetRepoSummary_Call struct {
	*mock.Call
}

// GetRepoSummary is a helper method to define mock.On call
//   - workspace string
//   - repo string
func (_e *Cache_Expecter) GetRepoSummary(workspace interface{}, repo interface{}) *Cache_GetRepoSummary_Call {
	return &Cache_GetRepoSummary_Call{Call: _e.mock.On("GetRepoSummary", workspace, repo)}
}

func (_c *Cache_GetRepoSummary_Call) Run(run func(workspace string, repo string)) *Cache_GetRepoSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetRepoSummary_Call) Return(repoSummary types.RepoSummary, b bool) *Cache_GetRepoSummary_Call {
	_c.Call.Return(repoSummary, b)
	return _c
}

func (_c *Cache_GetRepoSummary_Call) RunAndReturn(run func(workspace string, repo string) (types.RepoSummary, bool)) *Cache_GetRepoSummary_Call {
	_c.Call.Return(run)
	return _c
}

// SetWorkspace provides a mock function for the type Cache
func (_mock *Cache) SetWorkspace(name string, data types.CacheWorkspaceData) {
	_mock.Called(name, data)
	return
}

// Cache_SetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWorkspace'
type Cache_SetWorkspace_Call struct {
	*mock.Call
}

// SetWorkspace is a helper method to define mock.On call
//   - name string
//   - data types.CacheWorkspaceData
func (_e *Cache_Expecter) SetWorkspace(name interface{}, data interface{}) *Cache_SetWorkspace_Call {
	return &Cache_SetWorkspace_Call{Call: _e.mock.On("SetWorkspace", name, data)}
}

func (_c *Cache_SetWorkspace_Call) Run(run func(name string, data types.CacheWorkspaceData)) *Cache_SetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 types.CacheWorkspaceData
		if args[1] != nil {
			arg1 = args[1].(types.CacheWorkspaceData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_SetWorkspace_Call) Return() *Cache_SetWorkspace_Call {
	_c.Call.Return()
	return _c
}

func (_c *Cache_SetWorkspace_Call) RunAndReturn(run func(name string, data types.CacheWorkspaceData)) *Cache_SetWorkspace_Call {
	_c.Run(run)
	return _c
}
