// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewGitInfo creates a new instance of GitInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitInfo {
	mock := &GitInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitInfo is an autogenerated mock type for the GitInfo type
type GitInfo struct {
	mock.Mock
}

type GitInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *GitInfo) EXPECT() *GitInfo_Expecter {
	return &GitInfo_Expecter{mock: &_m.Mock}
}

// RepoInfo provides a mock function for the type GitInfo
func (_mock *GitInfo) RepoInfo(repoPath string) (types.RepoSummary, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for RepoInfo")
	}

	var r0 types.RepoSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.RepoSummary, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.RepoSummary); ok {
		r0 = returnFunc(repoPath)
	} else {
		r0 = ret.Get(0).(types.RepoSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GitInfo_RepoInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepoInfo'
type GitInfo_RepoInfo_Call struct {
	*mock.Call
}

// RepoInfo is a helper method to define mock.On call
//   - repoPath string
func (_e *GitInfo_Expecter) RepoInfo(repoPath interface{}) *GitInfo_RepoInfo_Call {
	return &GitInfo_RepoInfo_Call{Call: _e.mock.On("RepoInfo", repoPath)}
}

func (_c *GitInfo_RepoInfo_Call) Run(run func(repoPath string)) *GitInfo_RepoInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GitInfo_RepoInfo_Call) Return(repoSummary types.RepoSummary, err error) *GitInfo_RepoInfo_Call {
	_c.Call.Return(repoSummary, err)
	return _c
}

func (_c *GitInfo_RepoInfo_Call) RunAndReturn(run func(repoPath string) (types.RepoSummary, error)) *GitInfo_RepoInfo_Call {
	_c.Call.Return(run)
	return _c
}
