// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewWorkspaceDiscovery creates a new instance of WorkspaceDiscovery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkspaceDiscovery(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkspaceDiscovery {
	mock := &WorkspaceDiscovery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkspaceDiscovery is an autogenerated mock type for the WorkspaceDiscovery type
type WorkspaceDiscovery struct {
	mock.Mock
}

type WorkspaceDiscovery_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkspaceDiscovery) EXPECT() *WorkspaceDiscovery_Expecter {
	return &WorkspaceDiscovery_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type WorkspaceDiscovery
func (_mock *WorkspaceDiscovery) Get(basedir string, name string) (types.WorkspacePageData, error) {
	ret := _mock.Called(basedir, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 types.WorkspacePageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (types.WorkspacePageData, error)); ok {
		return returnFunc(basedir, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) types.WorkspacePageData); ok {
		r0 = returnFunc(basedir, name)
	} else {
		r0 = ret.Get(0).(types.WorkspacePageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(basedir, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceDiscovery_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WorkspaceDiscovery_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - basedir string
//   - name string
func (_e *WorkspaceDiscovery_Expecter) Get(basedir interface{}, name interface{}) *WorkspaceDiscovery_Get_Call {
	return &WorkspaceDiscovery_Get_Call{Call: _e.mock.On("Get", basedir, name)}
}

func (_c *WorkspaceDiscovery_Get_Call) Run(run func(basedir string, name string)) *WorkspaceDiscovery_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkspaceDiscovery_Get_Call) Return(workspacePageData types.WorkspacePageData, err error) *WorkspaceDiscovery_Get_Call {
	_c.Call.Return(workspacePageData, err)
	return _c
}

func (_c *WorkspaceDiscovery_Get_Call) RunAndReturn(run func(basedir string, name string) (types.WorkspacePageData, error)) *WorkspaceDiscovery_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type WorkspaceDiscovery
func (_mock *WorkspaceDiscovery) List(basedir string) ([]types.WorkspaceSummary, error) {
	ret := _mock.Called(basedir)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []types.WorkspaceSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]types.WorkspaceSummary, error)); ok {
		return returnFunc(basedir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []types.WorkspaceSummary); ok {
		r0 = returnFunc(basedir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.WorkspaceSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(basedir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceDiscovery_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type WorkspaceDiscovery_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - basedir string
func (_e *WorkspaceDiscovery_Expecter) List(basedir interface{}) *WorkspaceDiscovery_List_Call {
	return &WorkspaceDiscovery_List_Call{Call: _e.mock.On("List", basedir)}
}

func (_c *WorkspaceDiscovery_List_Call) Run(run func(basedir string)) *WorkspaceDiscovery_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WorkspaceDiscovery_List_Call) Return(workspaceSummarys []types.WorkspaceSummary, err error) *WorkspaceDiscovery_List_Call {
	_c.Call.Return(workspaceSummarys, err)
	return _c
}

func (_c *WorkspaceDiscovery_List_Call) RunAndReturn(run func(basedir string) ([]types.WorkspaceSummary, error)) *WorkspaceDiscovery_List_Call {
	_c.Call.Return(run)
	return _c
}
