// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkspaceAPIClient creates a new instance of MockWorkspaceAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceAPIClient {
	mock := &MockWorkspaceAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkspaceAPIClient is an autogenerated mock type for the WorkspaceAPIClient type
type MockWorkspaceAPIClient struct {
	mock.Mock
}

type MockWorkspaceAPIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceAPIClient) EXPECT() *MockWorkspaceAPIClient_Expecter {
	return &MockWorkspaceAPIClient_Expecter{mock: &_m.Mock}
}

// CreateWorkspace provides a mock function for the type MockWorkspaceAPIClient
func (_mock *MockWorkspaceAPIClient) CreateWorkspace(namespace string, req types.CreateManagedWorkspaceRequest) (*types.ManagedWorkspaceDetail, error) {
	ret := _mock.Called(namespace, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkspace")
	}

	var r0 *types.ManagedWorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, types.CreateManagedWorkspaceRequest) (*types.ManagedWorkspaceDetail, error)); ok {
		return returnFunc(namespace, req)
	}
	if returnFunc, ok := ret.Get(0).(func(string, types.CreateManagedWorkspaceRequest) *types.ManagedWorkspaceDetail); ok {
		r0 = returnFunc(namespace, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ManagedWorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, types.CreateManagedWorkspaceRequest) error); ok {
		r1 = returnFunc(namespace, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceAPIClient_CreateWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkspace'
type MockWorkspaceAPIClient_CreateWorkspace_Call struct {
	*mock.Call
}

// CreateWorkspace is a helper method to define mock.On call
//   - namespace string
//   - req types.CreateManagedWorkspaceRequest
func (_e *MockWorkspaceAPIClient_Expecter) CreateWorkspace(namespace interface{}, req interface{}) *MockWorkspaceAPIClient_CreateWorkspace_Call {
	return &MockWorkspaceAPIClient_CreateWorkspace_Call{Call: _e.mock.On("CreateWorkspace", namespace, req)}
}

func (_c *MockWorkspaceAPIClient_CreateWorkspace_Call) Run(run func(namespace string, req types.CreateManagedWorkspaceRequest)) *MockWorkspaceAPIClient_CreateWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 types.CreateManagedWorkspaceRequest
		if args[1] != nil {
			arg1 = args[1].(types.CreateManagedWorkspaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceAPIClient_CreateWorkspace_Call) Return(managedWorkspaceDetail *types.ManagedWorkspaceDetail, err error) *MockWorkspaceAPIClient_CreateWorkspace_Call {
	_c.Call.Return(managedWorkspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceAPIClient_CreateWorkspace_Call) RunAndReturn(run func(namespace string, req types.CreateManagedWorkspaceRequest) (*types.ManagedWorkspaceDetail, error)) *MockWorkspaceAPIClient_CreateWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkspace provides a mock function for the type MockWorkspaceAPIClient
func (_mock *MockWorkspaceAPIClient) DeleteWorkspace(namespace string, name string) error {
	ret := _mock.Called(namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(namespace, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceAPIClient_DeleteWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkspace'
type MockWorkspaceAPIClient_DeleteWorkspace_Call struct {
	*mock.Call
}

// DeleteWorkspace is a helper method to define mock.On call
//   - namespace string
//   - name string
func (_e *MockWorkspaceAPIClient_Expecter) DeleteWorkspace(namespace interface{}, name interface{}) *MockWorkspaceAPIClient_DeleteWorkspace_Call {
	return &MockWorkspaceAPIClient_DeleteWorkspace_Call{Call: _e.mock.On("DeleteWorkspace", namespace, name)}
}

func (_c *MockWorkspaceAPIClient_DeleteWorkspace_Call) Run(run func(namespace string, name string)) *MockWorkspaceAPIClient_DeleteWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceAPIClient_DeleteWorkspace_Call) Return(err error) *MockWorkspaceAPIClient_DeleteWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkspaceAPIClient_DeleteWorkspace_Call) RunAndReturn(run func(namespace string, name string) error) *MockWorkspaceAPIClient_DeleteWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspace provides a mock function for the type MockWorkspaceAPIClient
func (_mock *MockWorkspaceAPIClient) GetWorkspace(namespace string, name string) (*types.ManagedWorkspaceDetail, error) {
	ret := _mock.Called(namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 *types.ManagedWorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*types.ManagedWorkspaceDetail, error)); ok {
		return returnFunc(namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *types.ManagedWorkspaceDetail); ok {
		r0 = returnFunc(namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ManagedWorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceAPIClient_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type MockWorkspaceAPIClient_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - namespace string
//   - name string
func (_e *MockWorkspaceAPIClient_Expecter) GetWorkspace(namespace interface{}, name interface{}) *MockWorkspaceAPIClient_GetWorkspace_Call {
	return &MockWorkspaceAPIClient_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", namespace, name)}
}

func (_c *MockWorkspaceAPIClient_GetWorkspace_Call) Run(run func(namespace string, name string)) *MockWorkspaceAPIClient_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceAPIClient_GetWorkspace_Call) Return(managedWorkspaceDetail *types.ManagedWorkspaceDetail, err error) *MockWorkspaceAPIClient_GetWorkspace_Call {
	_c.Call.Return(managedWorkspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceAPIClient_GetWorkspace_Call) RunAndReturn(run func(namespace string, name string) (*types.ManagedWorkspaceDetail, error)) *MockWorkspaceAPIClient_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspaces provides a mock function for the type MockWorkspaceAPIClient
func (_mock *MockWorkspaceAPIClient) ListWorkspaces(namespace string) ([]types.ManagedWorkspaceSummary, error) {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspaces")
	}

	var r0 []types.ManagedWorkspaceSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]types.ManagedWorkspaceSummary, error)); ok {
		return returnFunc(namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []types.ManagedWorkspaceSummary); ok {
		r0 = returnFunc(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.ManagedWorkspaceSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceAPIClient_ListWorkspaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspaces'
type MockWorkspaceAPIClient_ListWorkspaces_Call struct {
	*mock.Call
}

// ListWorkspaces is a helper method to define mock.On call
//   - namespace string
func (_e *MockWorkspaceAPIClient_Expecter) ListWorkspaces(namespace interface{}) *MockWorkspaceAPIClient_ListWorkspaces_Call {
	return &MockWorkspaceAPIClient_ListWorkspaces_Call{Call: _e.mock.On("ListWorkspaces", namespace)}
}

func (_c *MockWorkspaceAPIClient_ListWorkspaces_Call) Run(run func(namespace string)) *MockWorkspaceAPIClient_ListWorkspaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorkspaceAPIClient_ListWorkspaces_Call) Return(managedWorkspaceSummarys []types.ManagedWorkspaceSummary, err error) *MockWorkspaceAPIClient_ListWorkspaces_Call {
	_c.Call.Return(managedWorkspaceSummarys, err)
	return _c
}

func (_c *MockWorkspaceAPIClient_ListWorkspaces_Call) RunAndReturn(run func(namespace string) ([]types.ManagedWorkspaceSummary, error)) *MockWorkspaceAPIClient_ListWorkspaces_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeWorkspace provides a mock function for the type MockWorkspaceAPIClient
func (_mock *MockWorkspaceAPIClient) ResumeWorkspace(namespace string, name string) (*types.ManagedWorkspaceDetail, error) {
	ret := _mock.Called(namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for ResumeWorkspace")
	}

	var r0 *types.ManagedWorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*types.ManagedWorkspaceDetail, error)); ok {
		return returnFunc(namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *types.ManagedWorkspaceDetail); ok {
		r0 = returnFunc(namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ManagedWorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceAPIClient_ResumeWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeWorkspace'
type MockWorkspaceAPIClient_ResumeWorkspace_Call struct {
	*mock.Call
}

// ResumeWorkspace is a helper method to define mock.On call
//   - namespace string
//   - name string
func (_e *MockWorkspaceAPIClient_Expecter) ResumeWorkspace(namespace interface{}, name interface{}) *MockWorkspaceAPIClient_ResumeWorkspace_Call {
	return &MockWorkspaceAPIClient_ResumeWorkspace_Call{Call: _e.mock.On("ResumeWorkspace", namespace, name)}
}

func (_c *MockWorkspaceAPIClient_ResumeWorkspace_Call) Run(run func(namespace string, name string)) *MockWorkspaceAPIClient_ResumeWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceAPIClient_ResumeWorkspace_Call) Return(managedWorkspaceDetail *types.ManagedWorkspaceDetail, err error) *MockWorkspaceAPIClient_ResumeWorkspace_Call {
	_c.Call.Return(managedWorkspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceAPIClient_ResumeWorkspace_Call) RunAndReturn(run func(namespace string, name string) (*types.ManagedWorkspaceDetail, error)) *MockWorkspaceAPIClient_ResumeWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// SuspendWorkspace provides a mock function for the type MockWorkspaceAPIClient
func (_mock *MockWorkspaceAPIClient) SuspendWorkspace(namespace string, name string) (*types.ManagedWorkspaceDetail, error) {
	ret := _mock.Called(namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for SuspendWorkspace")
	}

	var r0 *types.ManagedWorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*types.ManagedWorkspaceDetail, error)); ok {
		return returnFunc(namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *types.ManagedWorkspaceDetail); ok {
		r0 = returnFunc(namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ManagedWorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceAPIClient_SuspendWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuspendWorkspace'
type MockWorkspaceAPIClient_SuspendWorkspace_Call struct {
	*mock.Call
}

// SuspendWorkspace is a helper method to define mock.On call
//   - namespace string
//   - name string
func (_e *MockWorkspaceAPIClient_Expecter) SuspendWorkspace(namespace interface{}, name interface{}) *MockWorkspaceAPIClient_SuspendWorkspace_Call {
	return &MockWorkspaceAPIClient_SuspendWorkspace_Call{Call: _e.mock.On("SuspendWorkspace", namespace, name)}
}

func (_c *MockWorkspaceAPIClient_SuspendWorkspace_Call) Run(run func(namespace string, name string)) *MockWorkspaceAPIClient_SuspendWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceAPIClient_SuspendWorkspace_Call) Return(managedWorkspaceDetail *types.ManagedWorkspaceDetail, err error) *MockWorkspaceAPIClient_SuspendWorkspace_Call {
	_c.Call.Return(managedWorkspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceAPIClient_SuspendWorkspace_Call) RunAndReturn(run func(namespace string, name string) (*types.ManagedWorkspaceDetail, error)) *MockWorkspaceAPIClient_SuspendWorkspace_Call {
	_c.Call.Return(run)
	return _c
}
