// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockForgeLoader creates a new instance of MockForgeLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForgeLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForgeLoader {
	mock := &MockForgeLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockForgeLoader is an autogenerated mock type for the ForgeLoader type
type MockForgeLoader struct {
	mock.Mock
}

type MockForgeLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForgeLoader) EXPECT() *MockForgeLoader_Expecter {
	return &MockForgeLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockForgeLoader
func (_mock *MockForgeLoader) Load(repoPath string) (types.ForgePageData, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 types.ForgePageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.ForgePageData, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.ForgePageData); ok {
		r0 = returnFunc(repoPath)
	} else {
		r0 = ret.Get(0).(types.ForgePageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockForgeLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockForgeLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - repoPath string
func (_e *MockForgeLoader_Expecter) Load(repoPath interface{}) *MockForgeLoader_Load_Call {
	return &MockForgeLoader_Load_Call{Call: _e.mock.On("Load", repoPath)}
}

func (_c *MockForgeLoader_Load_Call) Run(run func(repoPath string)) *MockForgeLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockForgeLoader_Load_Call) Return(forgePageData types.ForgePageData, err error) *MockForgeLoader_Load_Call {
	_c.Call.Return(forgePageData, err)
	return _c
}

func (_c *MockForgeLoader_Load_Call) RunAndReturn(run func(repoPath string) (types.ForgePageData, error)) *MockForgeLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}
