// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepoPlanLoader creates a new instance of MockRepoPlanLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoPlanLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoPlanLoader {
	mock := &MockRepoPlanLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepoPlanLoader is an autogenerated mock type for the RepoPlanLoader type
type MockRepoPlanLoader struct {
	mock.Mock
}

type MockRepoPlanLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoPlanLoader) EXPECT() *MockRepoPlanLoader_Expecter {
	return &MockRepoPlanLoader_Expecter{mock: &_m.Mock}
}

// LoadAll provides a mock function for the type MockRepoPlanLoader
func (_mock *MockRepoPlanLoader) LoadAll(repoPath string) ([]types.RepoPlan, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 []types.RepoPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]types.RepoPlan, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []types.RepoPlan); ok {
		r0 = returnFunc(repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.RepoPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoPlanLoader_LoadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadAll'
type MockRepoPlanLoader_LoadAll_Call struct {
	*mock.Call
}

// LoadAll is a helper method to define mock.On call
//   - repoPath string
func (_e *MockRepoPlanLoader_Expecter) LoadAll(repoPath interface{}) *MockRepoPlanLoader_LoadAll_Call {
	return &MockRepoPlanLoader_LoadAll_Call{Call: _e.mock.On("LoadAll", repoPath)}
}

func (_c *MockRepoPlanLoader_LoadAll_Call) Run(run func(repoPath string)) *MockRepoPlanLoader_LoadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoPlanLoader_LoadAll_Call) Return(repoPlans []types.RepoPlan, err error) *MockRepoPlanLoader_LoadAll_Call {
	_c.Call.Return(repoPlans, err)
	return _c
}

func (_c *MockRepoPlanLoader_LoadAll_Call) RunAndReturn(run func(repoPath string) ([]types.RepoPlan, error)) *MockRepoPlanLoader_LoadAll_Call {
	_c.Call.Return(run)
	return _c
}

// LoadSummary provides a mock function for the type MockRepoPlanLoader
func (_mock *MockRepoPlanLoader) LoadSummary(repoPath string, repoName string) (types.RepoPlanSummary, error) {
	ret := _mock.Called(repoPath, repoName)

	if len(ret) == 0 {
		panic("no return value specified for LoadSummary")
	}

	var r0 types.RepoPlanSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (types.RepoPlanSummary, error)); ok {
		return returnFunc(repoPath, repoName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) types.RepoPlanSummary); ok {
		r0 = returnFunc(repoPath, repoName)
	} else {
		r0 = ret.Get(0).(types.RepoPlanSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(repoPath, repoName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoPlanLoader_LoadSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSummary'
type MockRepoPlanLoader_LoadSummary_Call struct {
	*mock.Call
}

// LoadSummary is a helper method to define mock.On call
//   - repoPath string
//   - repoName string
func (_e *MockRepoPlanLoader_Expecter) LoadSummary(repoPath interface{}, repoName interface{}) *MockRepoPlanLoader_LoadSummary_Call {
	return &MockRepoPlanLoader_LoadSummary_Call{Call: _e.mock.On("LoadSummary", repoPath, repoName)}
}

func (_c *MockRepoPlanLoader_LoadSummary_Call) Run(run func(repoPath string, repoName string)) *MockRepoPlanLoader_LoadSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoPlanLoader_LoadSummary_Call) Return(repoPlanSummary types.RepoPlanSummary, err error) *MockRepoPlanLoader_LoadSummary_Call {
	_c.Call.Return(repoPlanSummary, err)
	return _c
}

func (_c *MockRepoPlanLoader_LoadSummary_Call) RunAndReturn(run func(repoPath string, repoName string) (types.RepoPlanSummary, error)) *MockRepoPlanLoader_LoadSummary_Call {
	_c.Call.Return(run)
	return _c
}
