// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDataSource creates a new instance of MockDataSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataSource {
	mock := &MockDataSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataSource is an autogenerated mock type for the DataSource type
type MockDataSource struct {
	mock.Mock
}

type MockDataSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataSource) EXPECT() *MockDataSource_Expecter {
	return &MockDataSource_Expecter{mock: &_m.Mock}
}

// GetForge provides a mock function for the type MockDataSource
func (_mock *MockDataSource) GetForge(portfolio string, workspace string, repo string) (types.ForgePageData, error) {
	ret := _mock.Called(portfolio, workspace, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetForge")
	}

	var r0 types.ForgePageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (types.ForgePageData, error)); ok {
		return returnFunc(portfolio, workspace, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) types.ForgePageData); ok {
		r0 = returnFunc(portfolio, workspace, repo)
	} else {
		r0 = ret.Get(0).(types.ForgePageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(portfolio, workspace, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataSource_GetForge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForge'
type MockDataSource_GetForge_Call struct {
	*mock.Call
}

// GetForge is a helper method to define mock.On call
//   - portfolio string
//   - workspace string
//   - repo string
func (_e *MockDataSource_Expecter) GetForge(portfolio interface{}, workspace interface{}, repo interface{}) *MockDataSource_GetForge_Call {
	return &MockDataSource_GetForge_Call{Call: _e.mock.On("GetForge", portfolio, workspace, repo)}
}

func (_c *MockDataSource_GetForge_Call) Run(run func(portfolio string, workspace string, repo string)) *MockDataSource_GetForge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDataSource_GetForge_Call) Return(forgePageData types.ForgePageData, err error) *MockDataSource_GetForge_Call {
	_c.Call.Return(forgePageData, err)
	return _c
}

func (_c *MockDataSource_GetForge_Call) RunAndReturn(run func(portfolio string, workspace string, repo string) (types.ForgePageData, error)) *MockDataSource_GetForge_Call {
	_c.Call.Return(run)
	return _c
}

// GetPortfolio provides a mock function for the type MockDataSource
func (_mock *MockDataSource) GetPortfolio(name string, sort string) (types.PortfolioPageData, error) {
	ret := _mock.Called(name, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetPortfolio")
	}

	var r0 types.PortfolioPageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (types.PortfolioPageData, error)); ok {
		return returnFunc(name, sort)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) types.PortfolioPageData); ok {
		r0 = returnFunc(name, sort)
	} else {
		r0 = ret.Get(0).(types.PortfolioPageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(name, sort)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataSource_GetPortfolio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPortfolio'
type MockDataSource_GetPortfolio_Call struct {
	*mock.Call
}

// GetPortfolio is a helper method to define mock.On call
//   - name string
//   - sort string
func (_e *MockDataSource_Expecter) GetPortfolio(name interface{}, sort interface{}) *MockDataSource_GetPortfolio_Call {
	return &MockDataSource_GetPortfolio_Call{Call: _e.mock.On("GetPortfolio", name, sort)}
}

func (_c *MockDataSource_GetPortfolio_Call) Run(run func(name string, sort string)) *MockDataSource_GetPortfolio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataSource_GetPortfolio_Call) Return(portfolioPageData types.PortfolioPageData, err error) *MockDataSource_GetPortfolio_Call {
	_c.Call.Return(portfolioPageData, err)
	return _c
}

func (_c *MockDataSource_GetPortfolio_Call) RunAndReturn(run func(name string, sort string) (types.PortfolioPageData, error)) *MockDataSource_GetPortfolio_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspace provides a mock function for the type MockDataSource
func (_mock *MockDataSource) GetWorkspace(portfolio string, workspace string, sort string) (types.WorkspacePageData, error) {
	ret := _mock.Called(portfolio, workspace, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 types.WorkspacePageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (types.WorkspacePageData, error)); ok {
		return returnFunc(portfolio, workspace, sort)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) types.WorkspacePageData); ok {
		r0 = returnFunc(portfolio, workspace, sort)
	} else {
		r0 = ret.Get(0).(types.WorkspacePageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(portfolio, workspace, sort)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataSource_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type MockDataSource_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - portfolio string
//   - workspace string
//   - sort string
func (_e *MockDataSource_Expecter) GetWorkspace(portfolio interface{}, workspace interface{}, sort interface{}) *MockDataSource_GetWorkspace_Call {
	return &MockDataSource_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", portfolio, workspace, sort)}
}

func (_c *MockDataSource_GetWorkspace_Call) Run(run func(portfolio string, workspace string, sort string)) *MockDataSource_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDataSource_GetWorkspace_Call) Return(workspacePageData types.WorkspacePageData, err error) *MockDataSource_GetWorkspace_Call {
	_c.Call.Return(workspacePageData, err)
	return _c
}

func (_c *MockDataSource_GetWorkspace_Call) RunAndReturn(run func(portfolio string, workspace string, sort string) (types.WorkspacePageData, error)) *MockDataSource_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ListPortfolios provides a mock function for the type MockDataSource
func (_mock *MockDataSource) ListPortfolios(sort string) (types.PortfoliosPageData, error) {
	ret := _mock.Called(sort)

	if len(ret) == 0 {
		panic("no return value specified for ListPortfolios")
	}

	var r0 types.PortfoliosPageData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.PortfoliosPageData, error)); ok {
		return returnFunc(sort)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.PortfoliosPageData); ok {
		r0 = returnFunc(sort)
	} else {
		r0 = ret.Get(0).(types.PortfoliosPageData)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(sort)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataSource_ListPortfolios_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPortfolios'
type MockDataSource_ListPortfolios_Call struct {
	*mock.Call
}

// ListPortfolios is a helper method to define mock.On call
//   - sort string
func (_e *MockDataSource_Expecter) ListPortfolios(sort interface{}) *MockDataSource_ListPortfolios_Call {
	return &MockDataSource_ListPortfolios_Call{Call: _e.mock.On("ListPortfolios", sort)}
}

func (_c *MockDataSource_ListPortfolios_Call) Run(run func(sort string)) *MockDataSource_ListPortfolios_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataSource_ListPortfolios_Call) Return(portfoliosPageData types.PortfoliosPageData, err error) *MockDataSource_ListPortfolios_Call {
	_c.Call.Return(portfoliosPageData, err)
	return _c
}

func (_c *MockDataSource_ListPortfolios_Call) RunAndReturn(run func(sort string) (types.PortfoliosPageData, error)) *MockDataSource_ListPortfolios_Call {
	_c.Call.Return(run)
	return _c
}
