// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPortfolioConfigLoader creates a new instance of MockPortfolioConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPortfolioConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPortfolioConfigLoader {
	mock := &MockPortfolioConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPortfolioConfigLoader is an autogenerated mock type for the PortfolioConfigLoader type
type MockPortfolioConfigLoader struct {
	mock.Mock
}

type MockPortfolioConfigLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPortfolioConfigLoader) EXPECT() *MockPortfolioConfigLoader_Expecter {
	return &MockPortfolioConfigLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockPortfolioConfigLoader
func (_mock *MockPortfolioConfigLoader) Load(portfolioPath string) (types.PortfolioConfig, error) {
	ret := _mock.Called(portfolioPath)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 types.PortfolioConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.PortfolioConfig, error)); ok {
		return returnFunc(portfolioPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.PortfolioConfig); ok {
		r0 = returnFunc(portfolioPath)
	} else {
		r0 = ret.Get(0).(types.PortfolioConfig)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(portfolioPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortfolioConfigLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockPortfolioConfigLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - portfolioPath string
func (_e *MockPortfolioConfigLoader_Expecter) Load(portfolioPath interface{}) *MockPortfolioConfigLoader_Load_Call {
	return &MockPortfolioConfigLoader_Load_Call{Call: _e.mock.On("Load", portfolioPath)}
}

func (_c *MockPortfolioConfigLoader_Load_Call) Run(run func(portfolioPath string)) *MockPortfolioConfigLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPortfolioConfigLoader_Load_Call) Return(portfolioConfig types.PortfolioConfig, err error) *MockPortfolioConfigLoader_Load_Call {
	_c.Call.Return(portfolioConfig, err)
	return _c
}

func (_c *MockPortfolioConfigLoader_Load_Call) RunAndReturn(run func(portfolioPath string) (types.PortfolioConfig, error)) *MockPortfolioConfigLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}
