// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCUAdapter creates a new instance of MockCUAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCUAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCUAdapter {
	mock := &MockCUAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCUAdapter is an autogenerated mock type for the CUAdapter type
type MockCUAdapter struct {
	mock.Mock
}

type MockCUAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCUAdapter) EXPECT() *MockCUAdapter_Expecter {
	return &MockCUAdapter_Expecter{mock: &_m.Mock}
}

// LoadCompo provides a mock function for the type MockCUAdapter
func (_mock *MockCUAdapter) LoadCompo(cuRepoPath string) (types.CompoState, error) {
	ret := _mock.Called(cuRepoPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadCompo")
	}

	var r0 types.CompoState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.CompoState, error)); ok {
		return returnFunc(cuRepoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.CompoState); ok {
		r0 = returnFunc(cuRepoPath)
	} else {
		r0 = ret.Get(0).(types.CompoState)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(cuRepoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCUAdapter_LoadCompo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCompo'
type MockCUAdapter_LoadCompo_Call struct {
	*mock.Call
}

// LoadCompo is a helper method to define mock.On call
//   - cuRepoPath string
func (_e *MockCUAdapter_Expecter) LoadCompo(cuRepoPath interface{}) *MockCUAdapter_LoadCompo_Call {
	return &MockCUAdapter_LoadCompo_Call{Call: _e.mock.On("LoadCompo", cuRepoPath)}
}

func (_c *MockCUAdapter_LoadCompo_Call) Run(run func(cuRepoPath string)) *MockCUAdapter_LoadCompo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCUAdapter_LoadCompo_Call) Return(compoState types.CompoState, err error) *MockCUAdapter_LoadCompo_Call {
	_c.Call.Return(compoState, err)
	return _c
}

func (_c *MockCUAdapter_LoadCompo_Call) RunAndReturn(run func(cuRepoPath string) (types.CompoState, error)) *MockCUAdapter_LoadCompo_Call {
	_c.Call.Return(run)
	return _c
}
