// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWsConfigLoader creates a new instance of MockWsConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWsConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWsConfigLoader {
	mock := &MockWsConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWsConfigLoader is an autogenerated mock type for the WsConfigLoader type
type MockWsConfigLoader struct {
	mock.Mock
}

type MockWsConfigLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWsConfigLoader) EXPECT() *MockWsConfigLoader_Expecter {
	return &MockWsConfigLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockWsConfigLoader
func (_mock *MockWsConfigLoader) Load(wsPath string) (types.WsConfig, error) {
	ret := _mock.Called(wsPath)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 types.WsConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.WsConfig, error)); ok {
		return returnFunc(wsPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.WsConfig); ok {
		r0 = returnFunc(wsPath)
	} else {
		r0 = ret.Get(0).(types.WsConfig)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(wsPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWsConfigLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockWsConfigLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - wsPath string
func (_e *MockWsConfigLoader_Expecter) Load(wsPath interface{}) *MockWsConfigLoader_Load_Call {
	return &MockWsConfigLoader_Load_Call{Call: _e.mock.On("Load", wsPath)}
}

func (_c *MockWsConfigLoader_Load_Call) Run(run func(wsPath string)) *MockWsConfigLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWsConfigLoader_Load_Call) Return(wsConfig types.WsConfig, err error) *MockWsConfigLoader_Load_Call {
	_c.Call.Return(wsConfig, err)
	return _c
}

func (_c *MockWsConfigLoader_Load_Call) RunAndReturn(run func(wsPath string) (types.WsConfig, error)) *MockWsConfigLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}
