apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "forge-wss-proxy.fullname" . }}
  labels:
    {{- include "forge-wss-proxy.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "listenAddr": {{ .Values.config.listenAddr | quote }},
      "serveDir": {{ .Values.config.serveDir | quote }},
      "workspaceServicePattern": {{ .Values.config.workspaceServicePattern | quote }}
    }
