// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//go:build go1.22

// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ListPortfoliosParamsSort.
const (
	ListPortfoliosParamsSortName ListPortfoliosParamsSort = "name"
	ListPortfoliosParamsSortTime ListPortfoliosParamsSort = "time"
)

// Defines values for GetPortfolioParamsSort.
const (
	GetPortfolioParamsSortName GetPortfolioParamsSort = "name"
	GetPortfolioParamsSortTime GetPortfolioParamsSort = "time"
)

// Defines values for GetWorkspaceParamsSort.
const (
	Name GetWorkspaceParamsSort = "name"
	Time GetWorkspaceParamsSort = "time"
)

// Artifact defines model for Artifact.
type Artifact = types.Artifact

// ArtifactDependency defines model for ArtifactDependency.
type ArtifactDependency = types.ArtifactDependency

// BuildSpec defines model for BuildSpec.
type BuildSpec = types.BuildSpec

// CompoRepo defines model for CompoRepo.
type CompoRepo = types.CompoRepo

// CompoState defines model for CompoState.
type CompoState = types.CompoState

// Coverage defines model for Coverage.
type Coverage = types.Coverage

// CreateCompoInput defines model for CreateCompoInput.
type CreateCompoInput = types.CreateCompoInput

// CreateManagedWorkspaceRequest defines model for CreateManagedWorkspaceRequest.
type CreateManagedWorkspaceRequest = types.CreateManagedWorkspaceRequest

// CreateRepoInput defines model for CreateRepoInput.
type CreateRepoInput = types.CreateRepoInput

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ForgePageData defines model for ForgePageData.
type ForgePageData = types.ForgePageData

// ForgeSpec defines model for ForgeSpec.
type ForgeSpec = types.ForgeSpec

// ForgeStats defines model for ForgeStats.
type ForgeStats = types.ForgeStats

// LogEntry defines model for LogEntry.
type LogEntry = types.LogEntry

// ManagedCompoDetail defines model for ManagedCompoDetail.
type ManagedCompoDetail = types.ManagedCompoDetail

// ManagedCondition defines model for ManagedCondition.
type ManagedCondition = types.ManagedCondition

// ManagedRepoDetail defines model for ManagedRepoDetail.
type ManagedRepoDetail = types.ManagedRepoDetail

// ManagedStorageDetail defines model for ManagedStorageDetail.
type ManagedStorageDetail = types.ManagedStorageDetail

// ManagedWorkspaceDetail defines model for ManagedWorkspaceDetail.
type ManagedWorkspaceDetail = types.ManagedWorkspaceDetail

// ManagedWorkspaceSummary defines model for ManagedWorkspaceSummary.
type ManagedWorkspaceSummary = types.ManagedWorkspaceSummary

// MetaCheckpoint defines model for MetaCheckpoint.
type MetaCheckpoint = types.MetaCheckpoint

// MetaPlan defines model for MetaPlan.
type MetaPlan = types.MetaPlan

// MetaPlanStage defines model for MetaPlanStage.
type MetaPlanStage = types.MetaPlanStage

// PortfolioPageData defines model for PortfolioPageData.
type PortfolioPageData = types.PortfolioPageData

// PortfolioProgress defines model for PortfolioProgress.
type PortfolioProgress = types.PortfolioProgress

// PortfolioSummary defines model for PortfolioSummary.
type PortfolioSummary = types.PortfolioSummary

// PortfoliosPageData defines model for PortfoliosPageData.
type PortfoliosPageData = types.PortfoliosPageData

// PortfoliosStats defines model for PortfoliosStats.
type PortfoliosStats = types.PortfoliosStats

// RepoForgeStats defines model for RepoForgeStats.
type RepoForgeStats = types.RepoForgeStats

// RepoOverview defines model for RepoOverview.
type RepoOverview = types.RepoOverview

// RepoPlan defines model for RepoPlan.
type RepoPlan = types.RepoPlan

// RepoPlanSummary defines model for RepoPlanSummary.
type RepoPlanSummary = types.RepoPlanSummary

// RepoSummary defines model for RepoSummary.
type RepoSummary = types.RepoSummary

// SideNavItem defines model for SideNavItem.
type SideNavItem = types.SideNavItem

// StageRepo defines model for StageRepo.
type StageRepo = types.StageRepo

// StatusEntry defines model for StatusEntry.
type StatusEntry = types.StatusEntry

// TestEnv defines model for TestEnv.
type TestEnv = types.TestEnv

// TestReport defines model for TestReport.
type TestReport = types.TestReport

// TestSpec defines model for TestSpec.
type TestSpec = types.TestSpec

// TestStats defines model for TestStats.
type TestStats = types.TestStats

// WorkspacePageData defines model for WorkspacePageData.
type WorkspacePageData = types.WorkspacePageData

// WorkspaceProgress defines model for WorkspaceProgress.
type WorkspaceProgress = types.WorkspaceProgress

// WorkspaceStats defines model for WorkspaceStats.
type WorkspaceStats = types.WorkspaceStats

// WorkspaceSummary defines model for WorkspaceSummary.
type WorkspaceSummary = types.WorkspaceSummary

// WorkspacesStats defines model for WorkspacesStats.
type WorkspacesStats = types.WorkspacesStats

// ListManagedWorkspacesParams defines parameters for ListManagedWorkspaces.
type ListManagedWorkspacesParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// CreateManagedWorkspaceParams defines parameters for CreateManagedWorkspace.
type CreateManagedWorkspaceParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// DeleteManagedWorkspaceParams defines parameters for DeleteManagedWorkspace.
type DeleteManagedWorkspaceParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// GetManagedWorkspaceParams defines parameters for GetManagedWorkspace.
type GetManagedWorkspaceParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// ResumeManagedWorkspaceParams defines parameters for ResumeManagedWorkspace.
type ResumeManagedWorkspaceParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// SuspendManagedWorkspaceParams defines parameters for SuspendManagedWorkspace.
type SuspendManagedWorkspaceParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// ListPortfoliosParams defines parameters for ListPortfolios.
type ListPortfoliosParams struct {
	Sort *ListPortfoliosParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListPortfoliosParamsSort defines parameters for ListPortfolios.
type ListPortfoliosParamsSort string

// GetPortfolioParams defines parameters for GetPortfolio.
type GetPortfolioParams struct {
	Sort *GetPortfolioParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetPortfolioParamsSort defines parameters for GetPortfolio.
type GetPortfolioParamsSort string

// GetWorkspaceParams defines parameters for GetWorkspace.
type GetWorkspaceParams struct {
	Sort *GetWorkspaceParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetWorkspaceParamsSort defines parameters for GetWorkspace.
type GetWorkspaceParamsSort string

// CreateManagedWorkspaceJSONRequestBody defines body for CreateManagedWorkspace for application/json ContentType.
type CreateManagedWorkspaceJSONRequestBody = CreateManagedWorkspaceRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List managed workspaces from forge-workspace API
	// (GET /api/v1/managed-workspaces)
	ListManagedWorkspaces(w http.ResponseWriter, r *http.Request, params ListManagedWorkspacesParams)
	// Create a managed workspace
	// (POST /api/v1/managed-workspaces)
	CreateManagedWorkspace(w http.ResponseWriter, r *http.Request, params CreateManagedWorkspaceParams)
	// Delete a managed workspace
	// (DELETE /api/v1/managed-workspaces/{name})
	DeleteManagedWorkspace(w http.ResponseWriter, r *http.Request, name string, params DeleteManagedWorkspaceParams)
	// Get a managed workspace
	// (GET /api/v1/managed-workspaces/{name})
	GetManagedWorkspace(w http.ResponseWriter, r *http.Request, name string, params GetManagedWorkspaceParams)
	// Resume a managed workspace
	// (PUT /api/v1/managed-workspaces/{name}/resume)
	ResumeManagedWorkspace(w http.ResponseWriter, r *http.Request, name string, params ResumeManagedWorkspaceParams)
	// Suspend a managed workspace
	// (PUT /api/v1/managed-workspaces/{name}/suspend)
	SuspendManagedWorkspace(w http.ResponseWriter, r *http.Request, name string, params SuspendManagedWorkspaceParams)
	// List all portfolios
	// (GET /api/v1/portfolios)
	ListPortfolios(w http.ResponseWriter, r *http.Request, params ListPortfoliosParams)
	// Get a single portfolio by name
	// (GET /api/v1/portfolios/{name})
	GetPortfolio(w http.ResponseWriter, r *http.Request, name string, params GetPortfolioParams)
	// Get a single workspace within a portfolio
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace})
	GetWorkspace(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, params GetWorkspaceParams)
	// Get CU composition state for a workspace
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace}/cu)
	GetWorkspaceCU(w http.ResponseWriter, r *http.Request, portfolio string, workspace string)
	// Get forge data for a single repo
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace}/repos/{repo})
	GetRepo(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, repo string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListManagedWorkspaces operation middleware
func (siw *ServerInterfaceWrapper) ListManagedWorkspaces(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListManagedWorkspacesParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListManagedWorkspaces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateManagedWorkspace operation middleware
func (siw *ServerInterfaceWrapper) CreateManagedWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateManagedWorkspaceParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateManagedWorkspace(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteManagedWorkspace operation middleware
func (siw *ServerInterfaceWrapper) DeleteManagedWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteManagedWorkspaceParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteManagedWorkspace(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetManagedWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetManagedWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetManagedWorkspaceParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetManagedWorkspace(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ResumeManagedWorkspace operation middleware
func (siw *ServerInterfaceWrapper) ResumeManagedWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResumeManagedWorkspaceParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeManagedWorkspace(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SuspendManagedWorkspace operation middleware
func (siw *ServerInterfaceWrapper) SuspendManagedWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SuspendManagedWorkspaceParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SuspendManagedWorkspace(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListPortfolios operation middleware
func (siw *ServerInterfaceWrapper) ListPortfolios(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPortfoliosParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPortfolios(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPortfolio operation middleware
func (siw *ServerInterfaceWrapper) GetPortfolio(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPortfolioParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPortfolio(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "portfolio" -------------
	var portfolio string

	err = runtime.BindStyledParameterWithOptions("simple", "portfolio", r.PathValue("portfolio"), &portfolio, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "portfolio", Err: err})
		return
	}

	// ------------- Path parameter "workspace" -------------
	var workspace string

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, portfolio, workspace, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetWorkspaceCU operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspaceCU(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "portfolio" -------------
	var portfolio string

	err = runtime.BindStyledParameterWithOptions("simple", "portfolio", r.PathValue("portfolio"), &portfolio, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "portfolio", Err: err})
		return
	}

	// ------------- Path parameter "workspace" -------------
	var workspace string

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspaceCU(w, r, portfolio, workspace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRepo operation middleware
func (siw *ServerInterfaceWrapper) GetRepo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "portfolio" -------------
	var portfolio string

	err = runtime.BindStyledParameterWithOptions("simple", "portfolio", r.PathValue("portfolio"), &portfolio, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "portfolio", Err: err})
		return
	}

	// ------------- Path parameter "workspace" -------------
	var workspace string

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo string

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepo(w, r, portfolio, workspace, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/managed-workspaces", wrapper.ListManagedWorkspaces)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/managed-workspaces", wrapper.CreateManagedWorkspace)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/managed-workspaces/{name}", wrapper.DeleteManagedWorkspace)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/managed-workspaces/{name}", wrapper.GetManagedWorkspace)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/managed-workspaces/{name}/resume", wrapper.ResumeManagedWorkspace)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/managed-workspaces/{name}/suspend", wrapper.SuspendManagedWorkspace)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios", wrapper.ListPortfolios)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{name}", wrapper.GetPortfolio)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{portfolio}/workspaces/{workspace}", wrapper.GetWorkspace)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{portfolio}/workspaces/{workspace}/cu", wrapper.GetWorkspaceCU)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{portfolio}/workspaces/{workspace}/repos/{repo}", wrapper.GetRepo)

	return m
}

type ListManagedWorkspacesRequestObject struct {
	Params ListManagedWorkspacesParams
}

type ListManagedWorkspacesResponseObject interface {
	VisitListManagedWorkspacesResponse(w http.ResponseWriter) error
}

type ListManagedWorkspaces200JSONResponse []ManagedWorkspaceSummary

func (response ListManagedWorkspaces200JSONResponse) VisitListManagedWorkspacesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListManagedWorkspaces500JSONResponse ErrorResponse

func (response ListManagedWorkspaces500JSONResponse) VisitListManagedWorkspacesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateManagedWorkspaceRequestObject struct {
	Params CreateManagedWorkspaceParams
	Body   *CreateManagedWorkspaceJSONRequestBody
}

type CreateManagedWorkspaceResponseObject interface {
	VisitCreateManagedWorkspaceResponse(w http.ResponseWriter) error
}

type CreateManagedWorkspace201JSONResponse ManagedWorkspaceDetail

func (response CreateManagedWorkspace201JSONResponse) VisitCreateManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateManagedWorkspace400JSONResponse ErrorResponse

func (response CreateManagedWorkspace400JSONResponse) VisitCreateManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateManagedWorkspace500JSONResponse ErrorResponse

func (response CreateManagedWorkspace500JSONResponse) VisitCreateManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteManagedWorkspaceRequestObject struct {
	Name   string `json:"name"`
	Params DeleteManagedWorkspaceParams
}

type DeleteManagedWorkspaceResponseObject interface {
	VisitDeleteManagedWorkspaceResponse(w http.ResponseWriter) error
}

type DeleteManagedWorkspace204Response struct {
}

func (response DeleteManagedWorkspace204Response) VisitDeleteManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteManagedWorkspace404JSONResponse ErrorResponse

func (response DeleteManagedWorkspace404JSONResponse) VisitDeleteManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteManagedWorkspace500JSONResponse ErrorResponse

func (response DeleteManagedWorkspace500JSONResponse) VisitDeleteManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetManagedWorkspaceRequestObject struct {
	Name   string `json:"name"`
	Params GetManagedWorkspaceParams
}

type GetManagedWorkspaceResponseObject interface {
	VisitGetManagedWorkspaceResponse(w http.ResponseWriter) error
}

type GetManagedWorkspace200JSONResponse ManagedWorkspaceDetail

func (response GetManagedWorkspace200JSONResponse) VisitGetManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetManagedWorkspace404JSONResponse ErrorResponse

func (response GetManagedWorkspace404JSONResponse) VisitGetManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetManagedWorkspace500JSONResponse ErrorResponse

func (response GetManagedWorkspace500JSONResponse) VisitGetManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ResumeManagedWorkspaceRequestObject struct {
	Name   string `json:"name"`
	Params ResumeManagedWorkspaceParams
}

type ResumeManagedWorkspaceResponseObject interface {
	VisitResumeManagedWorkspaceResponse(w http.ResponseWriter) error
}

type ResumeManagedWorkspace200JSONResponse ManagedWorkspaceDetail

func (response ResumeManagedWorkspace200JSONResponse) VisitResumeManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResumeManagedWorkspace404JSONResponse ErrorResponse

func (response ResumeManagedWorkspace404JSONResponse) VisitResumeManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResumeManagedWorkspace500JSONResponse ErrorResponse

func (response ResumeManagedWorkspace500JSONResponse) VisitResumeManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SuspendManagedWorkspaceRequestObject struct {
	Name   string `json:"name"`
	Params SuspendManagedWorkspaceParams
}

type SuspendManagedWorkspaceResponseObject interface {
	VisitSuspendManagedWorkspaceResponse(w http.ResponseWriter) error
}

type SuspendManagedWorkspace200JSONResponse ManagedWorkspaceDetail

func (response SuspendManagedWorkspace200JSONResponse) VisitSuspendManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SuspendManagedWorkspace404JSONResponse ErrorResponse

func (response SuspendManagedWorkspace404JSONResponse) VisitSuspendManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SuspendManagedWorkspace500JSONResponse ErrorResponse

func (response SuspendManagedWorkspace500JSONResponse) VisitSuspendManagedWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListPortfoliosRequestObject struct {
	Params ListPortfoliosParams
}

type ListPortfoliosResponseObject interface {
	VisitListPortfoliosResponse(w http.ResponseWriter) error
}

type ListPortfolios200JSONResponse PortfoliosPageData

func (response ListPortfolios200JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListPortfolios400JSONResponse ErrorResponse

func (response ListPortfolios400JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListPortfolios500JSONResponse ErrorResponse

func (response ListPortfolios500JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolioRequestObject struct {
	Name   string `json:"name"`
	Params GetPortfolioParams
}

type GetPortfolioResponseObject interface {
	VisitGetPortfolioResponse(w http.ResponseWriter) error
}

type GetPortfolio200JSONResponse PortfolioPageData

func (response GetPortfolio200JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio400JSONResponse ErrorResponse

func (response GetPortfolio400JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio404JSONResponse ErrorResponse

func (response GetPortfolio404JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio500JSONResponse ErrorResponse

func (response GetPortfolio500JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceRequestObject struct {
	Portfolio string `json:"portfolio"`
	Workspace string `json:"workspace"`
	Params    GetWorkspaceParams
}

type GetWorkspaceResponseObject interface {
	VisitGetWorkspaceResponse(w http.ResponseWriter) error
}

type GetWorkspace200JSONResponse WorkspacePageData

func (response GetWorkspace200JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace400JSONResponse ErrorResponse

func (response GetWorkspace400JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace404JSONResponse ErrorResponse

func (response GetWorkspace404JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace500JSONResponse ErrorResponse

func (response GetWorkspace500JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceCURequestObject struct {
	Portfolio string `json:"portfolio"`
	Workspace string `json:"workspace"`
}

type GetWorkspaceCUResponseObject interface {
	VisitGetWorkspaceCUResponse(w http.ResponseWriter) error
}

type GetWorkspaceCU200JSONResponse CompoState

func (response GetWorkspaceCU200JSONResponse) VisitGetWorkspaceCUResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceCU500JSONResponse ErrorResponse

func (response GetWorkspaceCU500JSONResponse) VisitGetWorkspaceCUResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRepoRequestObject struct {
	Portfolio string `json:"portfolio"`
	Workspace string `json:"workspace"`
	Repo      string `json:"repo"`
}

type GetRepoResponseObject interface {
	VisitGetRepoResponse(w http.ResponseWriter) error
}

type GetRepo200JSONResponse ForgePageData

func (response GetRepo200JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRepo400JSONResponse ErrorResponse

func (response GetRepo400JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetRepo404JSONResponse ErrorResponse

func (response GetRepo404JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRepo500JSONResponse ErrorResponse

func (response GetRepo500JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List managed workspaces from forge-workspace API
	// (GET /api/v1/managed-workspaces)
	ListManagedWorkspaces(ctx context.Context, request ListManagedWorkspacesRequestObject) (ListManagedWorkspacesResponseObject, error)
	// Create a managed workspace
	// (POST /api/v1/managed-workspaces)
	CreateManagedWorkspace(ctx context.Context, request CreateManagedWorkspaceRequestObject) (CreateManagedWorkspaceResponseObject, error)
	// Delete a managed workspace
	// (DELETE /api/v1/managed-workspaces/{name})
	DeleteManagedWorkspace(ctx context.Context, request DeleteManagedWorkspaceRequestObject) (DeleteManagedWorkspaceResponseObject, error)
	// Get a managed workspace
	// (GET /api/v1/managed-workspaces/{name})
	GetManagedWorkspace(ctx context.Context, request GetManagedWorkspaceRequestObject) (GetManagedWorkspaceResponseObject, error)
	// Resume a managed workspace
	// (PUT /api/v1/managed-workspaces/{name}/resume)
	ResumeManagedWorkspace(ctx context.Context, request ResumeManagedWorkspaceRequestObject) (ResumeManagedWorkspaceResponseObject, error)
	// Suspend a managed workspace
	// (PUT /api/v1/managed-workspaces/{name}/suspend)
	SuspendManagedWorkspace(ctx context.Context, request SuspendManagedWorkspaceRequestObject) (SuspendManagedWorkspaceResponseObject, error)
	// List all portfolios
	// (GET /api/v1/portfolios)
	ListPortfolios(ctx context.Context, request ListPortfoliosRequestObject) (ListPortfoliosResponseObject, error)
	// Get a single portfolio by name
	// (GET /api/v1/portfolios/{name})
	GetPortfolio(ctx context.Context, request GetPortfolioRequestObject) (GetPortfolioResponseObject, error)
	// Get a single workspace within a portfolio
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace})
	GetWorkspace(ctx context.Context, request GetWorkspaceRequestObject) (GetWorkspaceResponseObject, error)
	// Get CU composition state for a workspace
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace}/cu)
	GetWorkspaceCU(ctx context.Context, request GetWorkspaceCURequestObject) (GetWorkspaceCUResponseObject, error)
	// Get forge data for a single repo
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace}/repos/{repo})
	GetRepo(ctx context.Context, request GetRepoRequestObject) (GetRepoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListManagedWorkspaces operation middleware
func (sh *strictHandler) ListManagedWorkspaces(w http.ResponseWriter, r *http.Request, params ListManagedWorkspacesParams) {
	var request ListManagedWorkspacesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListManagedWorkspaces(ctx, request.(ListManagedWorkspacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListManagedWorkspaces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListManagedWorkspacesResponseObject); ok {
		if err := validResponse.VisitListManagedWorkspacesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateManagedWorkspace operation middleware
func (sh *strictHandler) CreateManagedWorkspace(w http.ResponseWriter, r *http.Request, params CreateManagedWorkspaceParams) {
	var request CreateManagedWorkspaceRequestObject

	request.Params = params

	var body CreateManagedWorkspaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateManagedWorkspace(ctx, request.(CreateManagedWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateManagedWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateManagedWorkspaceResponseObject); ok {
		if err := validResponse.VisitCreateManagedWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteManagedWorkspace operation middleware
func (sh *strictHandler) DeleteManagedWorkspace(w http.ResponseWriter, r *http.Request, name string, params DeleteManagedWorkspaceParams) {
	var request DeleteManagedWorkspaceRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteManagedWorkspace(ctx, request.(DeleteManagedWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteManagedWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteManagedWorkspaceResponseObject); ok {
		if err := validResponse.VisitDeleteManagedWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetManagedWorkspace operation middleware
func (sh *strictHandler) GetManagedWorkspace(w http.ResponseWriter, r *http.Request, name string, params GetManagedWorkspaceParams) {
	var request GetManagedWorkspaceRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetManagedWorkspace(ctx, request.(GetManagedWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetManagedWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetManagedWorkspaceResponseObject); ok {
		if err := validResponse.VisitGetManagedWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeManagedWorkspace operation middleware
func (sh *strictHandler) ResumeManagedWorkspace(w http.ResponseWriter, r *http.Request, name string, params ResumeManagedWorkspaceParams) {
	var request ResumeManagedWorkspaceRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeManagedWorkspace(ctx, request.(ResumeManagedWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeManagedWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeManagedWorkspaceResponseObject); ok {
		if err := validResponse.VisitResumeManagedWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SuspendManagedWorkspace operation middleware
func (sh *strictHandler) SuspendManagedWorkspace(w http.ResponseWriter, r *http.Request, name string, params SuspendManagedWorkspaceParams) {
	var request SuspendManagedWorkspaceRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SuspendManagedWorkspace(ctx, request.(SuspendManagedWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SuspendManagedWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SuspendManagedWorkspaceResponseObject); ok {
		if err := validResponse.VisitSuspendManagedWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPortfolios operation middleware
func (sh *strictHandler) ListPortfolios(w http.ResponseWriter, r *http.Request, params ListPortfoliosParams) {
	var request ListPortfoliosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPortfolios(ctx, request.(ListPortfoliosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPortfolios")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPortfoliosResponseObject); ok {
		if err := validResponse.VisitListPortfoliosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPortfolio operation middleware
func (sh *strictHandler) GetPortfolio(w http.ResponseWriter, r *http.Request, name string, params GetPortfolioParams) {
	var request GetPortfolioRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPortfolio(ctx, request.(GetPortfolioRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPortfolio")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPortfolioResponseObject); ok {
		if err := validResponse.VisitGetPortfolioResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspace operation middleware
func (sh *strictHandler) GetWorkspace(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, params GetWorkspaceParams) {
	var request GetWorkspaceRequestObject

	request.Portfolio = portfolio
	request.Workspace = workspace
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspace(ctx, request.(GetWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkspaceResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspaceCU operation middleware
func (sh *strictHandler) GetWorkspaceCU(w http.ResponseWriter, r *http.Request, portfolio string, workspace string) {
	var request GetWorkspaceCURequestObject

	request.Portfolio = portfolio
	request.Workspace = workspace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspaceCU(ctx, request.(GetWorkspaceCURequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspaceCU")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkspaceCUResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceCUResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRepo operation middleware
func (sh *strictHandler) GetRepo(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, repo string) {
	var request GetRepoRequestObject

	request.Portfolio = portfolio
	request.Workspace = workspace
	request.Repo = repo

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRepo(ctx, request.(GetRepoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRepo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRepoResponseObject); ok {
		if err := validResponse.VisitGetRepoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xczXLbOBJ+FRZ3j7Ll7GQvviV2ZspVSdZlJTWHVA4Q2ZIwJgEGAJV4XXr3LYAQfwEK",
	"kARNlPXJskCC6A9fN/qPeo4TmheUABE8vn6OebKCHKmPb5jAC5QI+blgtAAmMKiRFAogKZBE/48F5OrD",
	"Pxks4uv4H9Nm0qmecbqd7nZ781O8mcTiqYD4OkaMIfV/RhMkMCVyNj3GBcNkKQcJysE4IHAOXKC8MI+q",
	"LwwDa2Dc/KxmZXT+FyQinsQ/Lpb0Qn8p//DLGqDW4AXOC8oqzJBYxdfxEotVOb9MaD5FGfxAJGWQo1W6",
	"QrTE0wVlS7go8RQTAYygbKrmViswIDbYCvhR3XaPkke0NIu5wBncq8UYBjnka2DHQ9ULuZZkgTB8W+Is",
	"nRWQmFjMhVEyIEtMwI+BnCX7gtEsMRAGN1IZH6CgQwxyRNAS0t9x1tNky3Y3impFomTZvkg0Cw2JxEwg",
	"AUMo5gyRZOULQ1IyBkS8VTf7UYZBQd3NZ4PNYBXu2FaiBwN3DUzboJ6RImieQdpCYU5pBojstE4FsASI",
	"0LMuKMuRiK/jlJbzTAqibyBlPgfmjIReZygcGCABCu87UpTCRjWzwIyucWoxyIeoVn9RQYX/UJmVPyl7",
	"5AVK4AG+ldradpFQRN9J/f7aN5MY57bTDhMsZgnDhdm4Z2gOmXo2SlMsXQ2U3XfWZNN5je4RVVrJJXW6",
	"FqtvXrigkqo3GeLmtekLZvi/cBg1bFsWlCeN7F46YrUWQZWnWWwgTN4xRtkD8IISbrKictgsAoNvJWbS",
	"wn7Rl3010PZ3+ex7tIRbJNBwfqSdMn+X3sRcicqCZph+HFOW0cH7DBH3xTzoO4xqhOcZJssHL/Wc4RQ+",
	"ovWdgNw4p3Yqx6ZQiCvXTqmqVFSBRMk/oOIwC8QFEtzt6epKOQdw8Y6s3eX/VN1gkl3OJcFkwm+66h7T",
	"jN+3dsfCCCc97RI8kJY2ezq0WdKTdwak8ft93Guhz1FnzM1PcMczZGTSYujQHK2XbY9yp+83iRcId71M",
	"+cRlNbZCvD3b0A0tEOe2m/kjLgrroFTrG1oSYR4XVKBMbgQ3jXvsg4Ip0Ea8p8t3RDBDgmGFuPmwzYFz",
	"sw/mJFP9xEASaX9GeY23IBDOvHwMyRcGKRCBUWZhTCBvw7Dy0BiR6hwy5AesmyyPaMQtiTquTrmjp40G",
	"6w2LizytAlHn1B7sUKKw0M2qsMSGHjeHK9145xBPwLiMsCLXkZNNaKdY16D8m0mcbBnv7m4NdMXgZNiD",
	"6KBRshxQSJlVYIX4MaLrIeXt8bXjXF06ydtLrhLYxtSWD1H75DkRVWdlniPTqW9nxtF39fgYbqUKBSII",
	"dLOC5LGgmBhzWq3j1OA2CfOZYC8tiAPcrN5iA0KiYu8hGPWzPTS3u2aD2qbAVYbPu1CosPRbiZRrprbA",
	"aD8sjo7z5ijYAm/LTBjT8kdKY6rZzZWJYwFUCRAIpfttpsqeGtvFN8xvYYHKzFe1rX4gp0x8oKmVxLuT",
	"P7U15HUGqM6xuO/twKbul0gYQhx8LxldMuCmvEIi8Bq2zOLmoF1CkYGAdMd1uj51Szv14nb0j/gj3zH8",
	"iYpOoNBPHoyuwRP/LSyh8bd6FqdXpfPVlsCOTP0cbrd8dRrfHYXB8k3HwsH2rVm83jE/aPnJLBG35DdT",
	"zMRTXZEYqv5YNnMsWVnvmDOCtVHYGpz7zqZbrNLI0sdTnnr8z45+HWbWeNDkqJR0LFMt3aX3mDz6V7l4",
	"5TrxMhMHBdtOaPXECAjWf9bA1hi+Gw7fFSALb+ewwsQ2NpptU0KZj4sV4p8LLhig3HwB5rdSD82DGeLi",
	"huY5Fp9w3qtCIAEXQn478Qg/rIfUKIWOUhvr7EvAvTeHgfZy1iH+kbPgIYOs7fxWj6c4Whl71JacDsnA",
	"bol8jBXM4xuQFC8W0iL+0tZFBinv6dKdhnV5zkJDq7GqAv5hQ+mODIIoueV5ztQMTMt2O8iwHIRSWzsa",
	"f6MCTgsHbDCSA0x9e6WhwKhzPu6mvtAnw99guZrlhsOjZrAhIZx6N+a7ilU/NZBg2yagoVCqJy59I9wN",
	"F07NGfFtoYbTkiVH60MfqUGXReq3dqfd2EIVcCd0/5SBYU1ry3gTub5Onnslq9+0cWiuUW2FH0baASy7",
	"a6teqBHmefQ5ZQZU09M2i3NY/rmFecBdNTeT2bPzJSG2N3aAC6i0dV9xQ7Z7NTszkHbfbMdoa5Y46NBo",
	"VhsIjjoDMtKTm2WzYclqp1HclWTN2xllr0qYlwm2t7k4NQfXnrdz4NTreDX4rU384vPuYj/ysUz+QLXX",
	"u3/ThF/pre32BsmyNhltjyTrkNfBFcha7dkyfaRBM2wNxxOxwPWZ3n56mWE170jW9zAzvXc62Q/g0xh0",
	"e/riF7XnLf1zMiftkoM0eSPqGeok8LOydep0v/zEqXqT+nXMc6o6/QQFpT58QXZpo15SXNBBNTx+eDf7",
	"FL25v4sWlEXbCaIa2klUVwImESJpJGkcpUigSxksYZFJSer73tzfxa3fOIjXry6vLq8kXLQAggocX8e/",
	"XV5d/hZXmq1gm6ICT9evpjoov+hWwZdV85oklIod79L4On6Puei34HE1J0M5CGA8vv7yHGO5hm8lKPJX",
	"JqbVMzjRvzxRgaIbAOpPw4D8q1Ti6k05tbJ/XV3p3jsBlSVBRZHh6sckpn/pRvXmGT4tpA5l/b6Njmdl",
	"kgDnizKLtuuUt/3bc5ljq+u+LmhYw51mXsSBrYFF1ZuBG9Vzqc8ntXmR3uyGXjxaMJprCtbfKkYpXecG",
	"GphfIz0JD9Sbqm9p+nQ0bMffid1037kUrITNgI+vjrYYS4+wYcfrSyKdnpPb9fqUnHuLpFnSMP2EfK82",
	"NkJDzqsL7eZv+ixJuql4mUH1CxJdDbhV3ztqgDpEOgoQ9znV1oVBOie8QX09PKAqCTWrXp9uZz9SES1o",
	"SdKfklMVKmZOTcxn5h8gfhmeXP0Nhs5yvL6QsiblHyD2t3JTBrysgkD94wxd+j6o4RcGH+WorrB+Mapd",
	"/lYUO4DC+r0iK4dn1fgLiY9C4uYtrhcat2msWbaTx90+a2uc3erMdQqseFW6NHFL11iBlHl8/WVLafXt",
	"19PyzdCU7XPkv0Q33WgeZVnUopOZZa1wxuag1ttyUpN4Xow9M8Ke1DDXIEXkDDxljskyg0ZxovlTpBhm",
	"05/682badj7qz6O65eduFC1N9Few7lzfW0/+/1DWYTn6RVlHPLkzUtYmM/0dixUmEWr0d3+9nSalk+re",
	"fD4T5Q2pXK2flT3jKohk1c3nSE3PVedOxKVMqhCHdrrsLqRSJefps/wzejLoLuVzOhS6c7FKgJ+Dnt1f",
	"BHyx+4NnS7qdgclXlUhV6tYqqU8ARbbNZrP5XwAAAP//WQEbK8hgAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
