//go:build go1.22

// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ListPortfoliosParamsSort.
const (
	ListPortfoliosParamsSortName ListPortfoliosParamsSort = "name"
	ListPortfoliosParamsSortTime ListPortfoliosParamsSort = "time"
)

// Defines values for GetPortfolioParamsSort.
const (
	GetPortfolioParamsSortName GetPortfolioParamsSort = "name"
	GetPortfolioParamsSortTime GetPortfolioParamsSort = "time"
)

// Defines values for GetWorkspaceParamsSort.
const (
	Name GetWorkspaceParamsSort = "name"
	Time GetWorkspaceParamsSort = "time"
)

// Artifact defines model for Artifact.
type Artifact = types.Artifact

// ArtifactDependency defines model for ArtifactDependency.
type ArtifactDependency = types.ArtifactDependency

// BuildSpec defines model for BuildSpec.
type BuildSpec = types.BuildSpec

// Coverage defines model for Coverage.
type Coverage = types.Coverage

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ForgePageData defines model for ForgePageData.
type ForgePageData = types.ForgePageData

// ForgeSpec defines model for ForgeSpec.
type ForgeSpec = types.ForgeSpec

// ForgeStats defines model for ForgeStats.
type ForgeStats = types.ForgeStats

// LogEntry defines model for LogEntry.
type LogEntry = types.LogEntry

// MetaCheckpoint defines model for MetaCheckpoint.
type MetaCheckpoint = types.MetaCheckpoint

// MetaPlan defines model for MetaPlan.
type MetaPlan = types.MetaPlan

// MetaPlanStage defines model for MetaPlanStage.
type MetaPlanStage = types.MetaPlanStage

// PortfolioPageData defines model for PortfolioPageData.
type PortfolioPageData = types.PortfolioPageData

// PortfolioProgress defines model for PortfolioProgress.
type PortfolioProgress = types.PortfolioProgress

// PortfolioSummary defines model for PortfolioSummary.
type PortfolioSummary = types.PortfolioSummary

// PortfoliosPageData defines model for PortfoliosPageData.
type PortfoliosPageData = types.PortfoliosPageData

// PortfoliosStats defines model for PortfoliosStats.
type PortfoliosStats = types.PortfoliosStats

// RepoForgeStats defines model for RepoForgeStats.
type RepoForgeStats = types.RepoForgeStats

// RepoOverview defines model for RepoOverview.
type RepoOverview = types.RepoOverview

// RepoPlan defines model for RepoPlan.
type RepoPlan = types.RepoPlan

// RepoPlanSummary defines model for RepoPlanSummary.
type RepoPlanSummary = types.RepoPlanSummary

// RepoSummary defines model for RepoSummary.
type RepoSummary = types.RepoSummary

// StageRepo defines model for StageRepo.
type StageRepo = types.StageRepo

// StatusEntry defines model for StatusEntry.
type StatusEntry = types.StatusEntry

// TestEnv defines model for TestEnv.
type TestEnv = types.TestEnv

// TestReport defines model for TestReport.
type TestReport = types.TestReport

// TestSpec defines model for TestSpec.
type TestSpec = types.TestSpec

// TestStats defines model for TestStats.
type TestStats = types.TestStats

// WorkspacePageData defines model for WorkspacePageData.
type WorkspacePageData = types.WorkspacePageData

// WorkspaceProgress defines model for WorkspaceProgress.
type WorkspaceProgress = types.WorkspaceProgress

// WorkspaceStats defines model for WorkspaceStats.
type WorkspaceStats = types.WorkspaceStats

// WorkspaceSummary defines model for WorkspaceSummary.
type WorkspaceSummary = types.WorkspaceSummary

// WorkspacesStats defines model for WorkspacesStats.
type WorkspacesStats = types.WorkspacesStats

// ListPortfoliosParams defines parameters for ListPortfolios.
type ListPortfoliosParams struct {
	Sort *ListPortfoliosParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListPortfoliosParamsSort defines parameters for ListPortfolios.
type ListPortfoliosParamsSort string

// GetPortfolioParams defines parameters for GetPortfolio.
type GetPortfolioParams struct {
	Sort *GetPortfolioParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetPortfolioParamsSort defines parameters for GetPortfolio.
type GetPortfolioParamsSort string

// GetWorkspaceParams defines parameters for GetWorkspace.
type GetWorkspaceParams struct {
	Sort *GetWorkspaceParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetWorkspaceParamsSort defines parameters for GetWorkspace.
type GetWorkspaceParamsSort string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all portfolios
	// (GET /api/v1/portfolios)
	ListPortfolios(w http.ResponseWriter, r *http.Request, params ListPortfoliosParams)
	// Get a single portfolio by name
	// (GET /api/v1/portfolios/{name})
	GetPortfolio(w http.ResponseWriter, r *http.Request, name string, params GetPortfolioParams)
	// Get a single workspace within a portfolio
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace})
	GetWorkspace(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, params GetWorkspaceParams)
	// Get forge data for a single repo
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace}/repos/{repo})
	GetRepo(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, repo string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListPortfolios operation middleware
func (siw *ServerInterfaceWrapper) ListPortfolios(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPortfoliosParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPortfolios(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPortfolio operation middleware
func (siw *ServerInterfaceWrapper) GetPortfolio(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPortfolioParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPortfolio(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "portfolio" -------------
	var portfolio string

	err = runtime.BindStyledParameterWithOptions("simple", "portfolio", r.PathValue("portfolio"), &portfolio, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "portfolio", Err: err})
		return
	}

	// ------------- Path parameter "workspace" -------------
	var workspace string

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, portfolio, workspace, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRepo operation middleware
func (siw *ServerInterfaceWrapper) GetRepo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "portfolio" -------------
	var portfolio string

	err = runtime.BindStyledParameterWithOptions("simple", "portfolio", r.PathValue("portfolio"), &portfolio, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "portfolio", Err: err})
		return
	}

	// ------------- Path parameter "workspace" -------------
	var workspace string

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo string

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepo(w, r, portfolio, workspace, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios", wrapper.ListPortfolios)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{name}", wrapper.GetPortfolio)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{portfolio}/workspaces/{workspace}", wrapper.GetWorkspace)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{portfolio}/workspaces/{workspace}/repos/{repo}", wrapper.GetRepo)

	return m
}

type ListPortfoliosRequestObject struct {
	Params ListPortfoliosParams
}

type ListPortfoliosResponseObject interface {
	VisitListPortfoliosResponse(w http.ResponseWriter) error
}

type ListPortfolios200JSONResponse PortfoliosPageData

func (response ListPortfolios200JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListPortfolios400JSONResponse ErrorResponse

func (response ListPortfolios400JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListPortfolios500JSONResponse ErrorResponse

func (response ListPortfolios500JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolioRequestObject struct {
	Name   string `json:"name"`
	Params GetPortfolioParams
}

type GetPortfolioResponseObject interface {
	VisitGetPortfolioResponse(w http.ResponseWriter) error
}

type GetPortfolio200JSONResponse PortfolioPageData

func (response GetPortfolio200JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio400JSONResponse ErrorResponse

func (response GetPortfolio400JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio404JSONResponse ErrorResponse

func (response GetPortfolio404JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio500JSONResponse ErrorResponse

func (response GetPortfolio500JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceRequestObject struct {
	Portfolio string `json:"portfolio"`
	Workspace string `json:"workspace"`
	Params    GetWorkspaceParams
}

type GetWorkspaceResponseObject interface {
	VisitGetWorkspaceResponse(w http.ResponseWriter) error
}

type GetWorkspace200JSONResponse WorkspacePageData

func (response GetWorkspace200JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace400JSONResponse ErrorResponse

func (response GetWorkspace400JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace404JSONResponse ErrorResponse

func (response GetWorkspace404JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace500JSONResponse ErrorResponse

func (response GetWorkspace500JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRepoRequestObject struct {
	Portfolio string `json:"portfolio"`
	Workspace string `json:"workspace"`
	Repo      string `json:"repo"`
}

type GetRepoResponseObject interface {
	VisitGetRepoResponse(w http.ResponseWriter) error
}

type GetRepo200JSONResponse ForgePageData

func (response GetRepo200JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRepo400JSONResponse ErrorResponse

func (response GetRepo400JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetRepo404JSONResponse ErrorResponse

func (response GetRepo404JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRepo500JSONResponse ErrorResponse

func (response GetRepo500JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all portfolios
	// (GET /api/v1/portfolios)
	ListPortfolios(ctx context.Context, request ListPortfoliosRequestObject) (ListPortfoliosResponseObject, error)
	// Get a single portfolio by name
	// (GET /api/v1/portfolios/{name})
	GetPortfolio(ctx context.Context, request GetPortfolioRequestObject) (GetPortfolioResponseObject, error)
	// Get a single workspace within a portfolio
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace})
	GetWorkspace(ctx context.Context, request GetWorkspaceRequestObject) (GetWorkspaceResponseObject, error)
	// Get forge data for a single repo
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace}/repos/{repo})
	GetRepo(ctx context.Context, request GetRepoRequestObject) (GetRepoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListPortfolios operation middleware
func (sh *strictHandler) ListPortfolios(w http.ResponseWriter, r *http.Request, params ListPortfoliosParams) {
	var request ListPortfoliosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPortfolios(ctx, request.(ListPortfoliosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPortfolios")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPortfoliosResponseObject); ok {
		if err := validResponse.VisitListPortfoliosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPortfolio operation middleware
func (sh *strictHandler) GetPortfolio(w http.ResponseWriter, r *http.Request, name string, params GetPortfolioParams) {
	var request GetPortfolioRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPortfolio(ctx, request.(GetPortfolioRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPortfolio")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPortfolioResponseObject); ok {
		if err := validResponse.VisitGetPortfolioResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspace operation middleware
func (sh *strictHandler) GetWorkspace(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, params GetWorkspaceParams) {
	var request GetWorkspaceRequestObject

	request.Portfolio = portfolio
	request.Workspace = workspace
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspace(ctx, request.(GetWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkspaceResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRepo operation middleware
func (sh *strictHandler) GetRepo(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, repo string) {
	var request GetRepoRequestObject

	request.Portfolio = portfolio
	request.Workspace = workspace
	request.Repo = repo

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRepo(ctx, request.(GetRepoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRepo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRepoResponseObject); ok {
		if err := validResponse.VisitGetRepoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbT1PbOBT/Kh7tHgOm2+4lNwq0wwzsZgg7PXR6UOwXR8WWXEkOZRi++45kW3ZiybET",
	"xJZuT4TIfpJ+7/ee3h/lEUUsyxkFKgWaPiIRrSDD+uMpl2SJI6k+55zlwCUBPRJDDjQGGlX/EwmZ/vA7",
	"hyWaot/CRmhYSQxrcef1yw/oaYLkQw5oijDnWP+fsghLwqiSVo0JyQlN1CDFGVgHJMlASJzl9lH9hWVg",
	"DVzY52pWxhZfIZJogr4fJeyo+lL9EccGoNbgEclyxkvMsFyhKUqIXBWL44hlIU7hO6Yxhwyv4hVmBQmX",
	"jCdwVJCQUAmc4jTUsvUKLIh1VAHfy9dmOLrDiX2bS5LCTC/GMiggWwN/PlRHIdfamScM3xckjec5RDYW",
	"C2ndGdCEUBjHQMGjfcFolugJgzO2Bl6RY4s9FC9SiFsrXzCWAqY7aZMDj4DKSuqS8QxLNEUxKxYpILNt",
	"WmQL4AOBMOv0hMMF54zfgMgZFTYw1LBdiRy+FYQroD5Xj33Z3tDTBH1Qc89wAudY4q58XJF+vMu0OUqF",
	"ypKlhP3loiSHvH9wlmI6fDE31Ru2xYjKwPre1+homqsXFHPmEstCXGPtX3AcE+X4cTrbQM3hd1qwC4ml",
	"GDa7flLJACEv6Hr45m/LF2x7V7IUNlyOE1e+Y5N4z/idyHEEDu0NMqZNMnqyqEanHbYvlFcbDEjjAy14",
	"uI/9yoMPxtw+w3A8fXrpFkO7rmOdtJ34Tnc7QUtMNh27mjEpx1ZYtKV1PX+OhXC9LO5InjsHlVmfsYJK",
	"+7hkEqdKEcI2PkIPGiZPirhiyQWV3BJsrbCwn4YZCGGPvgbtyczoaUfXIPHZCqK7nBFqiecjRkvn69ic",
	"tNPEHQzJA8DYWqxHSPRp1gXDzD3cn2+t2eLDYhARJ/n41EZjOW4lal9zrQLbUa0P3UOUo2HzrJa5tMar",
	"tC+cGQ6Slq7OX38AlRvwhNKsjv3cweYuvhFxDktcpGNNO3fmkYzLaxY7Sbw7RPtUhz3CxGkmEhquWyNl",
	"XmQZ5g97HvddiL3rkrOEg7Cd/pEka6iZJexHq4IiBQnxjueqxO2cbWS47TMaizuxY/hWneM9R3zvGkbi",
	"X8PiG/+aLz+AKb1ea6nF+FaWcHs+kxgPR6GzfNuxcLB/axZfaWwctOLFPJFwZCEx4fLhpj5pu6bfl3P0",
	"pRRGY4MRNE6hdjizDaU7vFLP0vsTk2r804Z9HebWhNcURu20L59U4dIVoXfj60aiDJ1EkZZy9y3bDEJr",
	"axsewfp7DXxN4N5y+K4AO3i7gBWhrjGOaWR37yss9Kbsx8UKi39yITngzP4AEefKDu2DKRbyjGUZkbck",
	"26oVYAlHUn07GZF+OA+pXgo9SwVrQy8edW9PA91Fp0Pio8Eb95lk1fKdEU/+bIXhXl/yckh6DkvUNE4w",
	"n9+BxGS5VB7xp/YuKkm5YslwGpoimoOGTmdVJvwfSAqjKgiyEI75BlPTMy2bMsdw75ZXzvA/MNZmuf7w",
	"MEqz1EDj0d3zodsys3raWN2d6m6KA5YQn8rhtkpiexEYU5xAfAOCFXw7w3QFe7s7OM5i2wQVeTxu7YO0",
	"UUPlURNVY8/CsKbn0udbTG9GufqCm+swA7o+ujd97WxGOLXrKtjrET7S2w9KhnU3ri5cHFZybWHuUav2",
	"Lqe7IF1Q6rpWA0JCaa37btdnH7LRTGe3+yb4vT1DedCh0azWExwm6e+52JGm826XZqdT3FVXzNpF1FHN",
	"n1Eu2BmDDbthYoLNwbnC1lUMS6jWhOxjLhhuB/sO4TesCvT2v3EyrtvUjvS8FBabIu6IumKX194NyNng",
	"qJnec3PAb9tiJGKeWxJb+hzlhrXcnkLnYW567wrqOIBfxqG7M/af1J+37G+QO2lX2ZXL6zFPXyfBOC9r",
	"qoX7peQdZvhm4CtstPwAPZRt+LxoSS2F0CXrNIDRzcX8NjidXQZLxoNaQGCgnQSm+D0JMI0DReMgxhIf",
	"q2SJyFTtxLx3OrtErR8ioPWb45PjEwUXy4HinKApent8cvwWlZatYQtxTsL1m3Cz1ZmU97QUkXTOeBmj",
	"KboiQraaY0oIxxlI4AJNPz8ioib9VoBme+lTdESCJtVPQUoAqv42qnI+oEWGpp/LF8ofCrRuRJt05osy",
	"4vK6tV7hHycn1XUzCaUnwXmekvIXH+FXUTrOZt5h3VQTwGilbSprXkQRCLEs0qBeicL23TMuZPNWuWUN",
	"77EiwbcChA4e/3zJuS8rXgcC+Bp4UF5eV8+J+vTTFAlwmgYtOqknuiwLH5XCn5xk+wgN1xxU02ZpmFbx",
	"p7leL3kBbeZ1EuSfgbGvjLDvTt693NwGpIAyGSxZQeMf0mg+ggxwIAhNUmgMJ1g8BJphLvsxn5/C5rZO",
	"+Gg+99qWOfgG2VbessTxBrYp67418//DWLvp8S9j7cxtQHpNxmq4HNwTuSI0wI397m+3oc5Wwkf1p9eI",
	"qwbXa7LfTVm83MBwMT7NdPNXTr9MtDO3otsrsE6dD+ksSadVxlg12VQ29m8AAAD//75ocxKoPgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
