//go:build go1.22

// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/alexandremahdhaoui/forge-ui/internal/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ListPortfoliosParamsSort.
const (
	ListPortfoliosParamsSortName ListPortfoliosParamsSort = "name"
	ListPortfoliosParamsSortTime ListPortfoliosParamsSort = "time"
)

// Defines values for GetPortfolioParamsSort.
const (
	GetPortfolioParamsSortName GetPortfolioParamsSort = "name"
	GetPortfolioParamsSortTime GetPortfolioParamsSort = "time"
)

// Defines values for GetWorkspaceParamsSort.
const (
	Name GetWorkspaceParamsSort = "name"
	Time GetWorkspaceParamsSort = "time"
)

// Artifact defines model for Artifact.
type Artifact = types.Artifact

// ArtifactDependency defines model for ArtifactDependency.
type ArtifactDependency = types.ArtifactDependency

// BuildSpec defines model for BuildSpec.
type BuildSpec = types.BuildSpec

// Coverage defines model for Coverage.
type Coverage = types.Coverage

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ForgePageData defines model for ForgePageData.
type ForgePageData = types.ForgePageData

// ForgeSpec defines model for ForgeSpec.
type ForgeSpec = types.ForgeSpec

// ForgeStats defines model for ForgeStats.
type ForgeStats = types.ForgeStats

// LogEntry defines model for LogEntry.
type LogEntry = types.LogEntry

// MetaCheckpoint defines model for MetaCheckpoint.
type MetaCheckpoint = types.MetaCheckpoint

// MetaPlan defines model for MetaPlan.
type MetaPlan = types.MetaPlan

// MetaPlanStage defines model for MetaPlanStage.
type MetaPlanStage = types.MetaPlanStage

// PortfolioPageData defines model for PortfolioPageData.
type PortfolioPageData = types.PortfolioPageData

// PortfolioProgress defines model for PortfolioProgress.
type PortfolioProgress = types.PortfolioProgress

// PortfolioSummary defines model for PortfolioSummary.
type PortfolioSummary = types.PortfolioSummary

// PortfoliosPageData defines model for PortfoliosPageData.
type PortfoliosPageData = types.PortfoliosPageData

// PortfoliosStats defines model for PortfoliosStats.
type PortfoliosStats = types.PortfoliosStats

// RepoForgeStats defines model for RepoForgeStats.
type RepoForgeStats = types.RepoForgeStats

// RepoOverview defines model for RepoOverview.
type RepoOverview = types.RepoOverview

// RepoPlan defines model for RepoPlan.
type RepoPlan = types.RepoPlan

// RepoPlanSummary defines model for RepoPlanSummary.
type RepoPlanSummary = types.RepoPlanSummary

// RepoSummary defines model for RepoSummary.
type RepoSummary = types.RepoSummary

// SideNavItem defines model for SideNavItem.
type SideNavItem = types.SideNavItem

// StageRepo defines model for StageRepo.
type StageRepo = types.StageRepo

// StatusEntry defines model for StatusEntry.
type StatusEntry = types.StatusEntry

// TestEnv defines model for TestEnv.
type TestEnv = types.TestEnv

// TestReport defines model for TestReport.
type TestReport = types.TestReport

// TestSpec defines model for TestSpec.
type TestSpec = types.TestSpec

// TestStats defines model for TestStats.
type TestStats = types.TestStats

// WorkspacePageData defines model for WorkspacePageData.
type WorkspacePageData = types.WorkspacePageData

// WorkspaceProgress defines model for WorkspaceProgress.
type WorkspaceProgress = types.WorkspaceProgress

// WorkspaceStats defines model for WorkspaceStats.
type WorkspaceStats = types.WorkspaceStats

// WorkspaceSummary defines model for WorkspaceSummary.
type WorkspaceSummary = types.WorkspaceSummary

// WorkspacesStats defines model for WorkspacesStats.
type WorkspacesStats = types.WorkspacesStats

// ListPortfoliosParams defines parameters for ListPortfolios.
type ListPortfoliosParams struct {
	Sort *ListPortfoliosParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListPortfoliosParamsSort defines parameters for ListPortfolios.
type ListPortfoliosParamsSort string

// GetPortfolioParams defines parameters for GetPortfolio.
type GetPortfolioParams struct {
	Sort *GetPortfolioParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetPortfolioParamsSort defines parameters for GetPortfolio.
type GetPortfolioParamsSort string

// GetWorkspaceParams defines parameters for GetWorkspace.
type GetWorkspaceParams struct {
	Sort *GetWorkspaceParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetWorkspaceParamsSort defines parameters for GetWorkspace.
type GetWorkspaceParamsSort string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all portfolios
	// (GET /api/v1/portfolios)
	ListPortfolios(w http.ResponseWriter, r *http.Request, params ListPortfoliosParams)
	// Get a single portfolio by name
	// (GET /api/v1/portfolios/{name})
	GetPortfolio(w http.ResponseWriter, r *http.Request, name string, params GetPortfolioParams)
	// Get a single workspace within a portfolio
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace})
	GetWorkspace(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, params GetWorkspaceParams)
	// Get forge data for a single repo
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace}/repos/{repo})
	GetRepo(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, repo string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListPortfolios operation middleware
func (siw *ServerInterfaceWrapper) ListPortfolios(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPortfoliosParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPortfolios(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPortfolio operation middleware
func (siw *ServerInterfaceWrapper) GetPortfolio(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPortfolioParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPortfolio(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "portfolio" -------------
	var portfolio string

	err = runtime.BindStyledParameterWithOptions("simple", "portfolio", r.PathValue("portfolio"), &portfolio, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "portfolio", Err: err})
		return
	}

	// ------------- Path parameter "workspace" -------------
	var workspace string

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, portfolio, workspace, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRepo operation middleware
func (siw *ServerInterfaceWrapper) GetRepo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "portfolio" -------------
	var portfolio string

	err = runtime.BindStyledParameterWithOptions("simple", "portfolio", r.PathValue("portfolio"), &portfolio, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "portfolio", Err: err})
		return
	}

	// ------------- Path parameter "workspace" -------------
	var workspace string

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo string

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepo(w, r, portfolio, workspace, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios", wrapper.ListPortfolios)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{name}", wrapper.GetPortfolio)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{portfolio}/workspaces/{workspace}", wrapper.GetWorkspace)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{portfolio}/workspaces/{workspace}/repos/{repo}", wrapper.GetRepo)

	return m
}

type ListPortfoliosRequestObject struct {
	Params ListPortfoliosParams
}

type ListPortfoliosResponseObject interface {
	VisitListPortfoliosResponse(w http.ResponseWriter) error
}

type ListPortfolios200JSONResponse PortfoliosPageData

func (response ListPortfolios200JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListPortfolios400JSONResponse ErrorResponse

func (response ListPortfolios400JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListPortfolios500JSONResponse ErrorResponse

func (response ListPortfolios500JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolioRequestObject struct {
	Name   string `json:"name"`
	Params GetPortfolioParams
}

type GetPortfolioResponseObject interface {
	VisitGetPortfolioResponse(w http.ResponseWriter) error
}

type GetPortfolio200JSONResponse PortfolioPageData

func (response GetPortfolio200JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio400JSONResponse ErrorResponse

func (response GetPortfolio400JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio404JSONResponse ErrorResponse

func (response GetPortfolio404JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio500JSONResponse ErrorResponse

func (response GetPortfolio500JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceRequestObject struct {
	Portfolio string `json:"portfolio"`
	Workspace string `json:"workspace"`
	Params    GetWorkspaceParams
}

type GetWorkspaceResponseObject interface {
	VisitGetWorkspaceResponse(w http.ResponseWriter) error
}

type GetWorkspace200JSONResponse WorkspacePageData

func (response GetWorkspace200JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace400JSONResponse ErrorResponse

func (response GetWorkspace400JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace404JSONResponse ErrorResponse

func (response GetWorkspace404JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace500JSONResponse ErrorResponse

func (response GetWorkspace500JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRepoRequestObject struct {
	Portfolio string `json:"portfolio"`
	Workspace string `json:"workspace"`
	Repo      string `json:"repo"`
}

type GetRepoResponseObject interface {
	VisitGetRepoResponse(w http.ResponseWriter) error
}

type GetRepo200JSONResponse ForgePageData

func (response GetRepo200JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRepo400JSONResponse ErrorResponse

func (response GetRepo400JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetRepo404JSONResponse ErrorResponse

func (response GetRepo404JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRepo500JSONResponse ErrorResponse

func (response GetRepo500JSONResponse) VisitGetRepoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all portfolios
	// (GET /api/v1/portfolios)
	ListPortfolios(ctx context.Context, request ListPortfoliosRequestObject) (ListPortfoliosResponseObject, error)
	// Get a single portfolio by name
	// (GET /api/v1/portfolios/{name})
	GetPortfolio(ctx context.Context, request GetPortfolioRequestObject) (GetPortfolioResponseObject, error)
	// Get a single workspace within a portfolio
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace})
	GetWorkspace(ctx context.Context, request GetWorkspaceRequestObject) (GetWorkspaceResponseObject, error)
	// Get forge data for a single repo
	// (GET /api/v1/portfolios/{portfolio}/workspaces/{workspace}/repos/{repo})
	GetRepo(ctx context.Context, request GetRepoRequestObject) (GetRepoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListPortfolios operation middleware
func (sh *strictHandler) ListPortfolios(w http.ResponseWriter, r *http.Request, params ListPortfoliosParams) {
	var request ListPortfoliosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPortfolios(ctx, request.(ListPortfoliosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPortfolios")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPortfoliosResponseObject); ok {
		if err := validResponse.VisitListPortfoliosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPortfolio operation middleware
func (sh *strictHandler) GetPortfolio(w http.ResponseWriter, r *http.Request, name string, params GetPortfolioParams) {
	var request GetPortfolioRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPortfolio(ctx, request.(GetPortfolioRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPortfolio")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPortfolioResponseObject); ok {
		if err := validResponse.VisitGetPortfolioResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspace operation middleware
func (sh *strictHandler) GetWorkspace(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, params GetWorkspaceParams) {
	var request GetWorkspaceRequestObject

	request.Portfolio = portfolio
	request.Workspace = workspace
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspace(ctx, request.(GetWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkspaceResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRepo operation middleware
func (sh *strictHandler) GetRepo(w http.ResponseWriter, r *http.Request, portfolio string, workspace string, repo string) {
	var request GetRepoRequestObject

	request.Portfolio = portfolio
	request.Workspace = workspace
	request.Repo = repo

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRepo(ctx, request.(GetRepoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRepo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRepoResponseObject); ok {
		if err := validResponse.VisitGetRepoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbz27bOBN/FYHfd3SidNu9+JYmaREg6RpxFj0UPdDSWGYjkSpJOQ2CvPuClETJFilL",
	"dphtuj3VDaXh8Df/Z6hHFLEsZxSoFGj6iES0ggzrn6dckiWOpPqdc5YDlwT0Sgw50BhoVP2fSMj0j/9z",
	"WKIp+l/YEA0rimFN7rx++QE9TZB8yAFNEeYc6/+nLMKSMKqoVWtCckITtUhxBtYFSTIQEme5fVX/wbKw",
	"Bi7sezWcscU3iCSaoB9HCTuq/qj+EccGoNbiEclyxkvMsFyhKUqIXBWL44hlIU7hB6Yxhwyv4hVmBQmX",
	"jCdwVJCQUAmc4jTUtDUHFsQ6ooAf5WszHN3hxH7MJUlhppmxLArI1sCfD9VRyLVO5gnD9wVJ43kOkU2L",
	"hbSeDGhCKIzTQMGjfcFoWPSEwRlbA6+UY0t7KF6kELc4XzCWAqY71SYHHgGVFdUl4xmWaIpiVixSQObY",
	"tMgWwAcCYfj0hMMF54zfgMgZFTYw1LJdiBy+F4QroL5Uj33dPtDTBH1Qe89wAudY4i59XCn9eJdpc5QK",
	"lSVLCfvkUkkOef/iLMV0ODM31Rs2ZgRZpIQm6pHhBOckhk94fSkhs9KsjLaPhEZcm456QWnjXGJZiGus",
	"fRaOY6KCCU5nG5Jw+LKWKIXEUgzbXT+paICQF3Q9/Py35Qu2sytaCkwux5Er37FRvGf8TuQ4AodGDDLQ",
	"TQX3ZKWNTDsWtFCecjAgjV+14OFOJaqoMBhz+w7D8fTp+Vsa2nVH66QdGHa68AlaYrIZLNSOSbm2wqJN",
	"rRtNciyE62VxR/LcuajM+owVVNrXJZM4VYIQtvURctAweRLEFUsuqOSWBG6FhT3CZiCEPaMbdCazo6cT",
	"XYPEZyuI7nJGqKVGiBgtna/jcNKuJu4ESx4AxhazHiHREbILhtl7uD/f4tniw2IQESf5+HJJYzmOE3Wu",
	"uRaBLVTroHuIcDRsnsUyl9YcmPalSCOyGUVdxV9/AJUH8ITSrM4n3QnsLn0j4hyWuEjHmnburE0Zl9cs",
	"dirx7hTtc532CJOnmUxouGwNlXmRZZg/7BnuuxB7lyVnCQdhi/6RJGuoNUvYQ6uCIgUJ8Y7nqmLwnG1U",
	"ze0YjcWd2LF8q+J4T4jv5WEk/jUsvvGv9eUnMKXXay01Gd/CEm7PZ4rt4Sh02LeFhYP9W8N8JbFx0IoX",
	"80TCUYXEhMsH0zfomn5fzdFXUhiJDUbQOIXa4cw2hO7wSj2s9xcm1frnDfs6zK0JryWMOmlfPanSpStC",
	"78b3okSZOokiLenu27YZhNbWMTyC9dca+JrAvSX4rgA79HYBK0JdaxzTyO7eV1joQ9nDxQqLv3MhOeDM",
	"/gAR58oO7YspFvKMZRmRtyTb6hVgCUdS/XUyovxwBqleFXqWDtaGXDzK3l4GuptOh+RHgw/us8iq6Tsz",
	"nvzZms29vuTlkPSclqhtnGA+vwOJyXKpPOIv7V1UkXLFkuFqaJpoDjV0Oquy4P9AUhjVQZCFcOw3WDU9",
	"q2V7aNPtz+PYMYIm4lQXnA4dcMFID3D1bU59gWF6PsNdfV5Fhn/BczXs+sPDaLClIRyPvp4w9FhmV08H",
	"q0d13UNxwBLiUznccZHY3hHHFCcQ34BgBd8ut12Z7+5xlrPzOEFFHo/jfZA0aqg8SqKaclo0rBlA9Tla",
	"M6hSca/g5r7RgBGYHv5fOyczTum6phd6hY8MfYM6A3o0WXdxDus/tzD3KFX7yNfdnS8odd1bAiGhtNZ9",
	"j+tzKNtIpnPafbsdvQNUeVDQaLj1BIfpgPTcnEnTeXdktdMp7mqyZu2O8qhJ2CgX7ExIh13hMZn34MJp",
	"616KJW9t6pcxNzi3Kx8H8RtWZb37X78ZN3prp71euqxNR3tEk7Wr194NyDntqTW95xqF3xnOSMQ8z2e2",
	"5DnKDWu6PV3fw9z03u3kcQC/jEN3ty9+UX/esr9B7qQ9clAur8c8fUWCcV7WtE736090NMO3Br7CqdNP",
	"MFDahs+LlBQrhC5ZZxqObi7mt8Hp7DJYMh7UBAID7SQwk4BJgGkcKDUOYizxsSqWiEzVScx7p7NL1PrS",
	"A63fHJ8cnyi4WA4U5wRN0dvjk+O3qLRsDVuIcxKu34Sbc9+kvLSmFEnXjJcxmqIrImRrUqiIcJyBBC7Q",
	"9MsjImrT7wVobS99is5I0KT61qYEoBr2o6rmA1pkaPqlfKH8EqN15dyUM1+VEZf32TWHf5ycVHfvJJSe",
	"BOd5SspPasJvonSczb7DRssmgdFC2xTWvIgiEGJZpEHNicL23TMysnlt38LDe6yU4HsBQiePf77k3peV",
	"XgcC+Bp4UH4doJ4TdfTTKhLgNA1a6qSe6GpZ+KgE/uRUto/Q6JpD1bRZGk2r9Kf5fkHyAtqa1ymQfwWN",
	"fWUK++7k3cvtbUAKKJPBkhU0/imN5iPIAAeC0CSFxnCCxUOgNcxlP+b3U9hcXQofze9e2zKBb5Bt5S1L",
	"HG9gm7TuWzv/N4y1Wx7/NtbO3gak12SsRpeDeyJXhAa4sd/97TbU1Ur4qP7pNeJqwPWa7HeTFi8PMJyM",
	"TzPd/OTrt4l29lbq9gqsU9dDukrSZZUxVq1sqhr7JwAA//8pwvB9CUAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
