FROM docker.io/golang:1.25 AS downloader

WORKDIR /workdir
COPY ./go.* ./
RUN go mod download

FROM downloader AS builder

ARG NAME=forge-ui
ARG INPUT_CMD="./cmd/${NAME}"
ARG OUTPUT_BIN="/bin/${NAME}"
WORKDIR /workdir
COPY . ./
RUN CGO_ENABLED=0 \
    GOOS=linux \
    go build \
      -buildvcs=false \
      -o "${OUTPUT_BIN}" \
      "${INPUT_CMD}"

FROM docker.io/alpine:3.20.1

RUN apk add --no-cache git

ARG NAME=forge-ui
ARG OUTPUT_BIN="/bin/${NAME}"
COPY --from=builder ${OUTPUT_BIN} ${OUTPUT_BIN}
COPY ./templates /templates

EXPOSE 8080
CMD [ "forge-ui", "-port", "8080" ]
